kind: pipeline
name: default

steps:
- name: lint
  image: arduino/arduino-cli:drone-1.0
  commands:
    # Check if the Go code is properly formatted and run the linter
    - task check
    # Ensure protobufs compile
    - task protoc

- name: build
  image: arduino/arduino-cli:drone-1.0
  commands:
    - task build

- name: test
  image: arduino/arduino-cli:drone-1.0
  commands:
    - task test-unit
    - task test-legacy

- name: integration
  image: arduino/arduino-cli:drone-1.0
  commands:
    - pip install -r test/requirements.txt
    - task test-integration

# Contrary to other CI platforms, uploading reports to Codecov requires Drone to provide a token.
# To avoid exposing the Codecov token to external PRs, we only upload coverage when we merge on
# `master`.
- name: coverage
  image: arduino/arduino-cli:drone-1.0
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
    - codecov -cF unit -f coverage_unit.txt -t $CODECOV_TOKEN
    - codecov -cF integ -f coverage_integ.txt -t $CODECOV_TOKEN
  when:
    branch:
      - master
    event:
      - push

- name: release
  image: arduino/arduino-cli:builder-1.0
  commands:
    # FIXME: run the real options
    - goreleaser --snapshot --skip-publish --skip-validation
  when:
    ref:
      - refs/tags/v*