= arduino-cli
Alessandro Sanino <a.sanino@arduino.cc>

https://drone.arduino.cc/bcmi-labs/arduino-cli[image:https://drone.arduino.cc/api/badges/bcmi-labs/arduino-cli/status.svg[Build Status]]

Arduino CLI is a tool to access all Arduino Create API from Command Line.
It implements all functions provided by web version of Arduino Create.

== Installation
 . You should have Go compiler installed and `GOPATH` environment variable set.
 . Run `go get github.com/bcmi-labs/arduino-cli` to install this repository under your `GOPATH`.


== Compiling
There are two ways to execute the project:

. By running the go main file.
+
[source, bash]
----
$ go run main.go ARGS
----
. By compiling then running the go program.
+
[source, bash]
----
$ go build -o arduino
$ ./arduino ARGS
----

You may want to copy the binary into a directory which is in your `PATH` environment variable
(such as `/usr/local/bin/`) or add the binary's directory to it.

Bash autocompletion and manpages can be generated with the `arduino generate-docs` command.

And you're done, now let's see how to use the CLI.

== Usage : An example

A general call is
[source, bash]
----
  $ arduino [COMMAND] [options]
----

To see the full list of commands, call one of the following:
[source, bash]
----
  $ arduino help [COMMAND]
  $ arduino [COMMAND] -h
  $ arduino [COMMAND] --help
----

Here is the output from help command `arduino help`:
----
Arduino Create Command Line Interface (arduino-cli).

Usage:
  arduino [command]

Examples:
arduino generate-docs # To generate the docs and autocompletion for the whole CLI.

Available Commands:
  board         Arduino board commands.
  compile       Compiles Arduino sketches.
  config        Arduino Configuration Commands.
  core          Arduino Core operations.
  generate-docs Generates documentation.
  help          Help about any command
  lib           Arduino commands about libraries.
  login         create default credentials for an Arduino Create Session.
  sketch        Arduino CLI Sketch Commands.
  version       Shows version number of arduino CLI.

Flags:
	  --config-file string   The custom config file (if not specified ./.cli-config.yml will be used). (default "/usr/local/bin/.cli-config.yml")
	  --debug                Enables debug output (super verbose, used to debug the CLI).
	  --format string        The output format, can be [text|json]. (default "text")
  -h, --help                 help for arduino

Use "arduino [command] --help" for more information about a command.
----

== Contributing

To contribute to this project:

. `git clone` this repository.
. Create a new branch with the name `feature-to-implement` or `bug-to-fix`.
. Code your contribution and push to your branch.
. Ask a Pull Request.

== Tips and Tricks
==== Download all libraries of the current library index:
[source, bash]
----
$ arduino lib search --names | tr "\n" " " | xargs arduino lib install
----
Same trick can be used on cores as well:
[source, bash]
----
$ arduino core search | tr "\n" " " | xargs arduino core install
----
And with the `download` command:
[source, bash]
----
$ arduino lib search --names | tr "\n" " " | xargs arduino lib download
$ arduino core search | tr "\n" " " | xargs arduino core download
----
