= arduino-cli
Alessandro Sanino <a.sanino@bcmi-labs.cc>

https://drone.arduino.cc/bcmi-labs/arduino-cli[image:https://drone.arduino.cc/api/badges/bcmi-labs/arduino-cli/status.svg[Build Status]]

Arduino CLI is a tool to access all Arduino Create API from Command Line.
It implements all functions provided by web version of Arduino Create.

== Installation 
 . `git clone` this repository into a folder of your choice
 . Add '/path/to/arduino-cli/folder' to your PATH environment variable
 . Reload shell configuration or reboot
 And you're done, now let's see how to use the CLI.

== Usage : An example

A general call is `arduino [COMMAND] [options]`
To see the full list of commands, call `arduino help [COMMAND]`, arduino [COMMAND] -h` or `arduino [COMMAND] --help`

== Contribution

To contribute to this project:

. `git clone` this repository
. Create a new branch with the name `feature-to-implement` or `bug-to-fix`
. Code your contribution and push to your branch
. Ask a Pull Request

== Tips and Tricks
==== Download all libraries of the current library index:
[source, bash]
----
$ arduino lib search | tr "\n" " " | xargs arduino lib install
----
Same trick can be used on cores as well:
[source, bash]
----
$ arduino core search | tr "\n" " " | xargs arduino core install
----
And with the `download` command:
[source, bash]
----
$ arduino lib search | tr "\n" " " | xargs arduino lib download
$ arduino core search | tr "\n" " " | xargs arduino core download
----