.TH "ARDUINO COMMAND LINE MANUAL" "1" "Jun 2017" "BCMI LABS SA" "" 
.nh
.ad l


.SH NAME
.PP
arduino\-lib \- Shows all commands regarding libraries.


.SH SYNOPSIS
.PP
\fBarduino lib [flags]\fP


.SH DESCRIPTION
.PP
Shows all commands regarding libraries.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for lib


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-v\fP, \fB\-\-verbose\fP[=0]
    enables verbose output (use more times for a higher level)


.SH SEE ALSO
.PP
\fBarduino(1)\fP, \fBarduino\-lib\-install(1)\fP, \fBarduino\-lib\-list(1)\fP, \fBarduino\-lib\-search(1)\fP, \fBarduino\-lib\-uninstall(1)\fP, \fBarduino\-lib\-version(1)\fP


.SH HISTORY
.PP
14\-Jun\-2017 BCMI LABS SA
