.TH "ARDUINO COMMAND LINE MANUAL" "1" "Jun 2017" "BCMI LABS SA" "" 
.nh
.ad l


.SH NAME
.PP
arduino\-lib\-search \- Searchs for a library data


.SH SYNOPSIS
.PP
\fBarduino lib search [flags]\fP


.SH DESCRIPTION
.PP
Search for one or more libraries data.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for search


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-v\fP, \fB\-\-verbose\fP[=0]
    enables verbose output (use more times for a higher level)


.SH SEE ALSO
.PP
\fBarduino\-lib(1)\fP


.SH HISTORY
.PP
14\-Jun\-2017 BCMI LABS SA
