.TH "ARDUINO COMMAND LINE MANUAL" "1" "Jun 2017" "BCMI LABS SA" "" 
.nh
.ad l


.SH NAME
.PP
arduino\-config \- A brief description of your command


.SH SYNOPSIS
.PP
\fBarduino config [flags]\fP


.SH DESCRIPTION
.PP
A longer description that spans multiple lines and likely contains examples
and usage of using your command. For example:

.PP
Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for config


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-v\fP, \fB\-\-verbose\fP[=0]
    enables verbose output (use more times for a higher level)


.SH SEE ALSO
.PP
\fBarduino(1)\fP


.SH HISTORY
.PP
14\-Jun\-2017 BCMI LABS SA
