.TH "ARDUINO COMMAND LINE MANUAL" "1" "Jun 2017" "BCMI LABS SA" "" 
.nh
.ad l


.SH NAME
.PP
arduino \- Arduino CLI


.SH SYNOPSIS
.PP
\fBarduino [flags]\fP


.SH DESCRIPTION
.PP
Arduino Create Command Line Interface (arduino\-cli)


.SH OPTIONS
.PP
\fB\-\-config\fP=""
    config file (default is $HOME/.arduino\-cli.yaml)

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for arduino

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=0]
    enables verbose output (use more times for a higher level)


.SH SEE ALSO
.PP
\fBarduino\-config(1)\fP, \fBarduino\-lib(1)\fP, \fBarduino\-version(1)\fP


.SH HISTORY
.PP
14\-Jun\-2017 BCMI LABS SA
