// Code generated by protoc-gen-go. DO NOT EDIT.
// source: board.proto

package rpc // import "github.com/arduino/arduino-cli/rpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BoardDetailsReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Fqbn                 string    `protobuf:"bytes,2,opt,name=fqbn,proto3" json:"fqbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BoardDetailsReq) Reset()         { *m = BoardDetailsReq{} }
func (m *BoardDetailsReq) String() string { return proto.CompactTextString(m) }
func (*BoardDetailsReq) ProtoMessage()    {}
func (*BoardDetailsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{0}
}
func (m *BoardDetailsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardDetailsReq.Unmarshal(m, b)
}
func (m *BoardDetailsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardDetailsReq.Marshal(b, m, deterministic)
}
func (dst *BoardDetailsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardDetailsReq.Merge(dst, src)
}
func (m *BoardDetailsReq) XXX_Size() int {
	return xxx_messageInfo_BoardDetailsReq.Size(m)
}
func (m *BoardDetailsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardDetailsReq.DiscardUnknown(m)
}

var xxx_messageInfo_BoardDetailsReq proto.InternalMessageInfo

func (m *BoardDetailsReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *BoardDetailsReq) GetFqbn() string {
	if m != nil {
		return m.Fqbn
	}
	return ""
}

type BoardDetailsResp struct {
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConfigOptions        []*ConfigOption `protobuf:"bytes,3,rep,name=config_options,json=configOptions,proto3" json:"config_options,omitempty"`
	RequiredTools        []*RequiredTool `protobuf:"bytes,4,rep,name=required_tools,json=requiredTools,proto3" json:"required_tools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BoardDetailsResp) Reset()         { *m = BoardDetailsResp{} }
func (m *BoardDetailsResp) String() string { return proto.CompactTextString(m) }
func (*BoardDetailsResp) ProtoMessage()    {}
func (*BoardDetailsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{1}
}
func (m *BoardDetailsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardDetailsResp.Unmarshal(m, b)
}
func (m *BoardDetailsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardDetailsResp.Marshal(b, m, deterministic)
}
func (dst *BoardDetailsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardDetailsResp.Merge(dst, src)
}
func (m *BoardDetailsResp) XXX_Size() int {
	return xxx_messageInfo_BoardDetailsResp.Size(m)
}
func (m *BoardDetailsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardDetailsResp.DiscardUnknown(m)
}

var xxx_messageInfo_BoardDetailsResp proto.InternalMessageInfo

func (m *BoardDetailsResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoardDetailsResp) GetConfigOptions() []*ConfigOption {
	if m != nil {
		return m.ConfigOptions
	}
	return nil
}

func (m *BoardDetailsResp) GetRequiredTools() []*RequiredTool {
	if m != nil {
		return m.RequiredTools
	}
	return nil
}

type ConfigOption struct {
	Option               string         `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	OptionLabel          string         `protobuf:"bytes,2,opt,name=option_label,json=optionLabel,proto3" json:"option_label,omitempty"`
	Values               []*ConfigValue `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConfigOption) Reset()         { *m = ConfigOption{} }
func (m *ConfigOption) String() string { return proto.CompactTextString(m) }
func (*ConfigOption) ProtoMessage()    {}
func (*ConfigOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{2}
}
func (m *ConfigOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigOption.Unmarshal(m, b)
}
func (m *ConfigOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigOption.Marshal(b, m, deterministic)
}
func (dst *ConfigOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigOption.Merge(dst, src)
}
func (m *ConfigOption) XXX_Size() int {
	return xxx_messageInfo_ConfigOption.Size(m)
}
func (m *ConfigOption) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigOption.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigOption proto.InternalMessageInfo

func (m *ConfigOption) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *ConfigOption) GetOptionLabel() string {
	if m != nil {
		return m.OptionLabel
	}
	return ""
}

func (m *ConfigOption) GetValues() []*ConfigValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type ConfigValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ValueLabel           string   `protobuf:"bytes,2,opt,name=value_label,json=valueLabel,proto3" json:"value_label,omitempty"`
	Selected             bool     `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigValue) Reset()         { *m = ConfigValue{} }
func (m *ConfigValue) String() string { return proto.CompactTextString(m) }
func (*ConfigValue) ProtoMessage()    {}
func (*ConfigValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{3}
}
func (m *ConfigValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigValue.Unmarshal(m, b)
}
func (m *ConfigValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigValue.Marshal(b, m, deterministic)
}
func (dst *ConfigValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigValue.Merge(dst, src)
}
func (m *ConfigValue) XXX_Size() int {
	return xxx_messageInfo_ConfigValue.Size(m)
}
func (m *ConfigValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigValue.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigValue proto.InternalMessageInfo

func (m *ConfigValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ConfigValue) GetValueLabel() string {
	if m != nil {
		return m.ValueLabel
	}
	return ""
}

func (m *ConfigValue) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

type RequiredTool struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Packager             string   `protobuf:"bytes,3,opt,name=packager,proto3" json:"packager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequiredTool) Reset()         { *m = RequiredTool{} }
func (m *RequiredTool) String() string { return proto.CompactTextString(m) }
func (*RequiredTool) ProtoMessage()    {}
func (*RequiredTool) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{4}
}
func (m *RequiredTool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequiredTool.Unmarshal(m, b)
}
func (m *RequiredTool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequiredTool.Marshal(b, m, deterministic)
}
func (dst *RequiredTool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequiredTool.Merge(dst, src)
}
func (m *RequiredTool) XXX_Size() int {
	return xxx_messageInfo_RequiredTool.Size(m)
}
func (m *RequiredTool) XXX_DiscardUnknown() {
	xxx_messageInfo_RequiredTool.DiscardUnknown(m)
}

var xxx_messageInfo_RequiredTool proto.InternalMessageInfo

func (m *RequiredTool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequiredTool) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RequiredTool) GetPackager() string {
	if m != nil {
		return m.Packager
	}
	return ""
}

type BoardAttachReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	BoardUri             string    `protobuf:"bytes,2,opt,name=board_uri,json=boardUri,proto3" json:"board_uri,omitempty"`
	SketchPath           string    `protobuf:"bytes,3,opt,name=sketch_path,json=sketchPath,proto3" json:"sketch_path,omitempty"`
	BoardFlavour         string    `protobuf:"bytes,4,opt,name=board_flavour,json=boardFlavour,proto3" json:"board_flavour,omitempty"`
	SearchTimeout        string    `protobuf:"bytes,5,opt,name=search_timeout,json=searchTimeout,proto3" json:"search_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BoardAttachReq) Reset()         { *m = BoardAttachReq{} }
func (m *BoardAttachReq) String() string { return proto.CompactTextString(m) }
func (*BoardAttachReq) ProtoMessage()    {}
func (*BoardAttachReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{5}
}
func (m *BoardAttachReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardAttachReq.Unmarshal(m, b)
}
func (m *BoardAttachReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardAttachReq.Marshal(b, m, deterministic)
}
func (dst *BoardAttachReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardAttachReq.Merge(dst, src)
}
func (m *BoardAttachReq) XXX_Size() int {
	return xxx_messageInfo_BoardAttachReq.Size(m)
}
func (m *BoardAttachReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardAttachReq.DiscardUnknown(m)
}

var xxx_messageInfo_BoardAttachReq proto.InternalMessageInfo

func (m *BoardAttachReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *BoardAttachReq) GetBoardUri() string {
	if m != nil {
		return m.BoardUri
	}
	return ""
}

func (m *BoardAttachReq) GetSketchPath() string {
	if m != nil {
		return m.SketchPath
	}
	return ""
}

func (m *BoardAttachReq) GetBoardFlavour() string {
	if m != nil {
		return m.BoardFlavour
	}
	return ""
}

func (m *BoardAttachReq) GetSearchTimeout() string {
	if m != nil {
		return m.SearchTimeout
	}
	return ""
}

type BoardAttachResp struct {
	TaskProgress         *TaskProgress `protobuf:"bytes,1,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BoardAttachResp) Reset()         { *m = BoardAttachResp{} }
func (m *BoardAttachResp) String() string { return proto.CompactTextString(m) }
func (*BoardAttachResp) ProtoMessage()    {}
func (*BoardAttachResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{6}
}
func (m *BoardAttachResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardAttachResp.Unmarshal(m, b)
}
func (m *BoardAttachResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardAttachResp.Marshal(b, m, deterministic)
}
func (dst *BoardAttachResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardAttachResp.Merge(dst, src)
}
func (m *BoardAttachResp) XXX_Size() int {
	return xxx_messageInfo_BoardAttachResp.Size(m)
}
func (m *BoardAttachResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardAttachResp.DiscardUnknown(m)
}

var xxx_messageInfo_BoardAttachResp proto.InternalMessageInfo

func (m *BoardAttachResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type BoardListReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BoardListReq) Reset()         { *m = BoardListReq{} }
func (m *BoardListReq) String() string { return proto.CompactTextString(m) }
func (*BoardListReq) ProtoMessage()    {}
func (*BoardListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{7}
}
func (m *BoardListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardListReq.Unmarshal(m, b)
}
func (m *BoardListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardListReq.Marshal(b, m, deterministic)
}
func (dst *BoardListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardListReq.Merge(dst, src)
}
func (m *BoardListReq) XXX_Size() int {
	return xxx_messageInfo_BoardListReq.Size(m)
}
func (m *BoardListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardListReq.DiscardUnknown(m)
}

var xxx_messageInfo_BoardListReq proto.InternalMessageInfo

func (m *BoardListReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

type BoardListResp struct {
	Ports                []*DetectedPort `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BoardListResp) Reset()         { *m = BoardListResp{} }
func (m *BoardListResp) String() string { return proto.CompactTextString(m) }
func (*BoardListResp) ProtoMessage()    {}
func (*BoardListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{8}
}
func (m *BoardListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardListResp.Unmarshal(m, b)
}
func (m *BoardListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardListResp.Marshal(b, m, deterministic)
}
func (dst *BoardListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardListResp.Merge(dst, src)
}
func (m *BoardListResp) XXX_Size() int {
	return xxx_messageInfo_BoardListResp.Size(m)
}
func (m *BoardListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardListResp.DiscardUnknown(m)
}

var xxx_messageInfo_BoardListResp proto.InternalMessageInfo

func (m *BoardListResp) GetPorts() []*DetectedPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

type DetectedPort struct {
	Address              string           `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Protocol             string           `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ProtocolLabel        string           `protobuf:"bytes,3,opt,name=protocol_label,json=protocolLabel,proto3" json:"protocol_label,omitempty"`
	Boards               []*BoardListItem `protobuf:"bytes,4,rep,name=boards,proto3" json:"boards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DetectedPort) Reset()         { *m = DetectedPort{} }
func (m *DetectedPort) String() string { return proto.CompactTextString(m) }
func (*DetectedPort) ProtoMessage()    {}
func (*DetectedPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{9}
}
func (m *DetectedPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectedPort.Unmarshal(m, b)
}
func (m *DetectedPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectedPort.Marshal(b, m, deterministic)
}
func (dst *DetectedPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectedPort.Merge(dst, src)
}
func (m *DetectedPort) XXX_Size() int {
	return xxx_messageInfo_DetectedPort.Size(m)
}
func (m *DetectedPort) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectedPort.DiscardUnknown(m)
}

var xxx_messageInfo_DetectedPort proto.InternalMessageInfo

func (m *DetectedPort) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DetectedPort) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *DetectedPort) GetProtocolLabel() string {
	if m != nil {
		return m.ProtocolLabel
	}
	return ""
}

func (m *DetectedPort) GetBoards() []*BoardListItem {
	if m != nil {
		return m.Boards
	}
	return nil
}

type BoardListAllReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	SearchArgs           []string  `protobuf:"bytes,2,rep,name=search_args,json=searchArgs,proto3" json:"search_args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BoardListAllReq) Reset()         { *m = BoardListAllReq{} }
func (m *BoardListAllReq) String() string { return proto.CompactTextString(m) }
func (*BoardListAllReq) ProtoMessage()    {}
func (*BoardListAllReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{10}
}
func (m *BoardListAllReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardListAllReq.Unmarshal(m, b)
}
func (m *BoardListAllReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardListAllReq.Marshal(b, m, deterministic)
}
func (dst *BoardListAllReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardListAllReq.Merge(dst, src)
}
func (m *BoardListAllReq) XXX_Size() int {
	return xxx_messageInfo_BoardListAllReq.Size(m)
}
func (m *BoardListAllReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardListAllReq.DiscardUnknown(m)
}

var xxx_messageInfo_BoardListAllReq proto.InternalMessageInfo

func (m *BoardListAllReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *BoardListAllReq) GetSearchArgs() []string {
	if m != nil {
		return m.SearchArgs
	}
	return nil
}

type BoardListAllResp struct {
	Boards               []*BoardListItem `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BoardListAllResp) Reset()         { *m = BoardListAllResp{} }
func (m *BoardListAllResp) String() string { return proto.CompactTextString(m) }
func (*BoardListAllResp) ProtoMessage()    {}
func (*BoardListAllResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{11}
}
func (m *BoardListAllResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardListAllResp.Unmarshal(m, b)
}
func (m *BoardListAllResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardListAllResp.Marshal(b, m, deterministic)
}
func (dst *BoardListAllResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardListAllResp.Merge(dst, src)
}
func (m *BoardListAllResp) XXX_Size() int {
	return xxx_messageInfo_BoardListAllResp.Size(m)
}
func (m *BoardListAllResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardListAllResp.DiscardUnknown(m)
}

var xxx_messageInfo_BoardListAllResp proto.InternalMessageInfo

func (m *BoardListAllResp) GetBoards() []*BoardListItem {
	if m != nil {
		return m.Boards
	}
	return nil
}

type BoardListItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FQBN                 string   `protobuf:"bytes,2,opt,name=FQBN,proto3" json:"FQBN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoardListItem) Reset()         { *m = BoardListItem{} }
func (m *BoardListItem) String() string { return proto.CompactTextString(m) }
func (*BoardListItem) ProtoMessage()    {}
func (*BoardListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_board_cfe40cb888280102, []int{12}
}
func (m *BoardListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardListItem.Unmarshal(m, b)
}
func (m *BoardListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardListItem.Marshal(b, m, deterministic)
}
func (dst *BoardListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardListItem.Merge(dst, src)
}
func (m *BoardListItem) XXX_Size() int {
	return xxx_messageInfo_BoardListItem.Size(m)
}
func (m *BoardListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardListItem.DiscardUnknown(m)
}

var xxx_messageInfo_BoardListItem proto.InternalMessageInfo

func (m *BoardListItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoardListItem) GetFQBN() string {
	if m != nil {
		return m.FQBN
	}
	return ""
}

func init() {
	proto.RegisterType((*BoardDetailsReq)(nil), "cc.arduino.core.rpc.BoardDetailsReq")
	proto.RegisterType((*BoardDetailsResp)(nil), "cc.arduino.core.rpc.BoardDetailsResp")
	proto.RegisterType((*ConfigOption)(nil), "cc.arduino.core.rpc.ConfigOption")
	proto.RegisterType((*ConfigValue)(nil), "cc.arduino.core.rpc.ConfigValue")
	proto.RegisterType((*RequiredTool)(nil), "cc.arduino.core.rpc.RequiredTool")
	proto.RegisterType((*BoardAttachReq)(nil), "cc.arduino.core.rpc.BoardAttachReq")
	proto.RegisterType((*BoardAttachResp)(nil), "cc.arduino.core.rpc.BoardAttachResp")
	proto.RegisterType((*BoardListReq)(nil), "cc.arduino.core.rpc.BoardListReq")
	proto.RegisterType((*BoardListResp)(nil), "cc.arduino.core.rpc.BoardListResp")
	proto.RegisterType((*DetectedPort)(nil), "cc.arduino.core.rpc.DetectedPort")
	proto.RegisterType((*BoardListAllReq)(nil), "cc.arduino.core.rpc.BoardListAllReq")
	proto.RegisterType((*BoardListAllResp)(nil), "cc.arduino.core.rpc.BoardListAllResp")
	proto.RegisterType((*BoardListItem)(nil), "cc.arduino.core.rpc.BoardListItem")
}

func init() { proto.RegisterFile("board.proto", fileDescriptor_board_cfe40cb888280102) }

var fileDescriptor_board_cfe40cb888280102 = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xdf, 0x4e, 0x14, 0x3f,
	0x14, 0xce, 0xfc, 0x80, 0xfd, 0xed, 0x9e, 0x9d, 0x41, 0x53, 0x8d, 0xd9, 0x60, 0x8c, 0x50, 0x35,
	0xe1, 0xc6, 0x25, 0xd1, 0x0b, 0xd4, 0x3b, 0xd0, 0x10, 0x48, 0x08, 0x62, 0x83, 0x46, 0xbd, 0x59,
	0xbb, 0xdd, 0xb2, 0xdb, 0x30, 0x33, 0x1d, 0xda, 0x0e, 0x2f, 0xe0, 0xc3, 0xf8, 0x0e, 0xbe, 0x87,
	0xef, 0x63, 0xff, 0xcd, 0x38, 0x24, 0x2b, 0x89, 0xe1, 0x6a, 0x7a, 0xbe, 0xf9, 0x7a, 0xfe, 0x7e,
	0xa7, 0x30, 0x9c, 0x4a, 0xaa, 0x66, 0xe3, 0x4a, 0x49, 0x23, 0xd1, 0x3d, 0xc6, 0xc6, 0xd6, 0xaa,
	0x45, 0x29, 0xc7, 0x4c, 0x2a, 0x3e, 0x56, 0x15, 0xdb, 0x48, 0x99, 0x2c, 0x0a, 0x59, 0x06, 0x0a,
	0xfe, 0x06, 0x77, 0xf6, 0xdd, 0x8d, 0x77, 0xdc, 0x50, 0x91, 0x6b, 0xc2, 0x2f, 0xd1, 0x6b, 0xe8,
	0x8b, 0x52, 0x1b, 0x5a, 0x32, 0x3e, 0x4a, 0x36, 0x93, 0xed, 0xe1, 0x8b, 0x47, 0xe3, 0x25, 0x8e,
	0xc6, 0x47, 0x91, 0x44, 0x5a, 0x3a, 0x42, 0xb0, 0x7a, 0x7e, 0x39, 0x2d, 0x47, 0xff, 0xd9, 0x6b,
	0x03, 0xe2, 0xcf, 0xf8, 0x67, 0x02, 0x77, 0xaf, 0x87, 0xd0, 0x95, 0x23, 0x96, 0xb4, 0xe0, 0x0d,
	0xd1, 0x9d, 0xd1, 0x21, 0xac, 0x33, 0x59, 0x9e, 0x8b, 0xf9, 0x44, 0x56, 0x46, 0xc8, 0x52, 0x8f,
	0x56, 0x36, 0x57, 0x6c, 0xf4, 0xad, 0xa5, 0xd1, 0xdf, 0x7a, 0xea, 0x7b, 0xcf, 0x24, 0x19, 0xeb,
	0x58, 0xda, 0x79, 0x52, 0xfc, 0xb2, 0x16, 0x8a, 0xcf, 0x26, 0x46, 0xca, 0x5c, 0x8f, 0x56, 0x6f,
	0xf0, 0x44, 0x22, 0xf5, 0xcc, 0x32, 0x49, 0xa6, 0x3a, 0x96, 0xc6, 0xdf, 0x13, 0x48, 0xbb, 0x91,
	0xd0, 0x03, 0xe8, 0x85, 0xec, 0x7c, 0x6b, 0x06, 0x24, 0x5a, 0x68, 0x0b, 0xd2, 0x70, 0x9a, 0xe4,
	0x74, 0xca, 0xf3, 0x58, 0xd8, 0x30, 0x60, 0xc7, 0x0e, 0x42, 0xaf, 0xa0, 0x77, 0x45, 0xf3, 0x9a,
	0x37, 0x75, 0x6d, 0xde, 0x50, 0xd7, 0x27, 0x47, 0x24, 0x91, 0x6f, 0x87, 0x34, 0xec, 0xc0, 0xe8,
	0x3e, 0xac, 0xf9, 0x1f, 0x31, 0x85, 0x60, 0xa0, 0xc7, 0x30, 0xf4, 0x87, 0x6b, 0x09, 0x80, 0x87,
	0x42, 0xfc, 0x0d, 0xe8, 0x6b, 0x9e, 0x73, 0x66, 0xf8, 0xcc, 0x66, 0x90, 0x6c, 0xf7, 0x49, 0x6b,
	0xe3, 0xcf, 0x90, 0x76, 0xdb, 0xd0, 0xce, 0x27, 0xe9, 0xcc, 0x67, 0x04, 0xff, 0x5f, 0x71, 0xa5,
	0x5d, 0xed, 0xc1, 0x79, 0x63, 0x3a, 0xcf, 0x15, 0x65, 0x17, 0x74, 0xce, 0x95, 0xf7, 0x3c, 0x20,
	0xad, 0x8d, 0x7f, 0x25, 0xb0, 0xee, 0xc7, 0xbf, 0x67, 0x0c, 0x65, 0x8b, 0x5b, 0x0a, 0xec, 0x21,
	0x0c, 0xbc, 0xc0, 0x27, 0xb5, 0x12, 0x31, 0x8b, 0xbe, 0x07, 0x3e, 0x2a, 0xe1, 0x3a, 0xa0, 0x2f,
	0xb8, 0x61, 0x8b, 0x49, 0x45, 0xcd, 0x22, 0x66, 0x02, 0x01, 0x3a, 0xb5, 0x08, 0x7a, 0x02, 0x59,
	0xb8, 0x7d, 0x9e, 0xd3, 0x2b, 0x59, 0x2b, 0x2b, 0x0b, 0x47, 0x49, 0x3d, 0x78, 0x10, 0x30, 0xf4,
	0x0c, 0xd6, 0x35, 0xa7, 0xca, 0x7a, 0x31, 0xa2, 0xe0, 0xb2, 0x36, 0xa3, 0x35, 0xcf, 0xca, 0x02,
	0x7a, 0x16, 0x40, 0xfc, 0x25, 0x2e, 0x4e, 0x53, 0x96, 0x15, 0xf5, 0x01, 0x64, 0x86, 0xea, 0x8b,
	0x89, 0xdd, 0xac, 0xb9, 0xe2, 0x5a, 0xc7, 0xe2, 0x96, 0xab, 0xee, 0xcc, 0x32, 0x4f, 0x23, 0x91,
	0xa4, 0xa6, 0x63, 0xe1, 0x23, 0x48, 0xbd, 0xeb, 0x63, 0xa1, 0xcd, 0xed, 0xfa, 0x85, 0x0f, 0x21,
	0xeb, 0xb8, 0xb2, 0x39, 0xee, 0xc2, 0x5a, 0x25, 0x95, 0x71, 0xb9, 0xfd, 0x7d, 0x23, 0xec, 0xa6,
	0x7a, 0x59, 0x9c, 0x5a, 0x26, 0x09, 0x7c, 0xfc, 0xc3, 0x6e, 0x42, 0x17, 0x77, 0x72, 0xa0, 0xb3,
	0x59, 0x5b, 0xa7, 0x95, 0x43, 0x34, 0xbd, 0x1c, 0xdc, 0xe3, 0xc2, 0x64, 0x23, 0xc3, 0xd6, 0x76,
	0xdd, 0x6d, 0xce, 0x51, 0xa8, 0x61, 0x4c, 0x59, 0x83, 0x06, 0xad, 0xbe, 0x81, 0x9e, 0x1f, 0x4a,
	0xb3, 0xb9, 0x78, 0x69, 0x9e, 0x6d, 0x69, 0x47, 0x86, 0x17, 0x24, 0xde, 0xc0, 0x45, 0x9c, 0x8c,
	0xfb, 0xb1, 0x97, 0xe7, 0xb7, 0x54, 0x9c, 0x13, 0x55, 0x90, 0x03, 0x55, 0x73, 0x6d, 0xeb, 0x59,
	0xf1, 0xa2, 0xf2, 0xd0, 0x9e, 0x45, 0xf0, 0x49, 0x7c, 0xde, 0xda, 0x70, 0xb6, 0xcb, 0x7f, 0xd2,
	0x4f, 0xfe, 0x39, 0xfd, 0xdd, 0xce, 0xc8, 0xdc, 0x8f, 0xa5, 0xbb, 0x68, 0xb1, 0x83, 0x0f, 0xfb,
	0x27, 0xcd, 0xfb, 0xe9, 0xce, 0xfb, 0x4f, 0xbf, 0xe2, 0xb9, 0x30, 0x8b, 0x7a, 0x6a, 0x23, 0x14,
	0x3b, 0x31, 0x5a, 0xf3, 0x7d, 0xce, 0x72, 0xb1, 0x63, 0x83, 0x4e, 0x7b, 0xbe, 0xd1, 0x2f, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xff, 0xd1, 0x7d, 0x00, 0x29, 0x06, 0x00, 0x00,
}
