// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package rpc // import "github.com/arduino/arduino-cli/rpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlatformInstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	PlatformPackage      string    `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage,proto3" json:"platform_package,omitempty"`
	Architecture         string    `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Version              string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlatformInstallReq) Reset()         { *m = PlatformInstallReq{} }
func (m *PlatformInstallReq) String() string { return proto.CompactTextString(m) }
func (*PlatformInstallReq) ProtoMessage()    {}
func (*PlatformInstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_95af83e17996f70c, []int{0}
}
func (m *PlatformInstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformInstallReq.Unmarshal(m, b)
}
func (m *PlatformInstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformInstallReq.Marshal(b, m, deterministic)
}
func (dst *PlatformInstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformInstallReq.Merge(dst, src)
}
func (m *PlatformInstallReq) XXX_Size() int {
	return xxx_messageInfo_PlatformInstallReq.Size(m)
}
func (m *PlatformInstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformInstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformInstallReq proto.InternalMessageInfo

func (m *PlatformInstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *PlatformInstallReq) GetPlatformPackage() string {
	if m != nil {
		return m.PlatformPackage
	}
	return ""
}

func (m *PlatformInstallReq) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *PlatformInstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PlatformInstallResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlatformInstallResp) Reset()         { *m = PlatformInstallResp{} }
func (m *PlatformInstallResp) String() string { return proto.CompactTextString(m) }
func (*PlatformInstallResp) ProtoMessage()    {}
func (*PlatformInstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_95af83e17996f70c, []int{1}
}
func (m *PlatformInstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformInstallResp.Unmarshal(m, b)
}
func (m *PlatformInstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformInstallResp.Marshal(b, m, deterministic)
}
func (dst *PlatformInstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformInstallResp.Merge(dst, src)
}
func (m *PlatformInstallResp) XXX_Size() int {
	return xxx_messageInfo_PlatformInstallResp.Size(m)
}
func (m *PlatformInstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformInstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformInstallResp proto.InternalMessageInfo

func (m *PlatformInstallResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

type PlatformDownloadReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	PlatformPackage      string    `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage,proto3" json:"platform_package,omitempty"`
	Architecture         string    `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Version              string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlatformDownloadReq) Reset()         { *m = PlatformDownloadReq{} }
func (m *PlatformDownloadReq) String() string { return proto.CompactTextString(m) }
func (*PlatformDownloadReq) ProtoMessage()    {}
func (*PlatformDownloadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_95af83e17996f70c, []int{2}
}
func (m *PlatformDownloadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformDownloadReq.Unmarshal(m, b)
}
func (m *PlatformDownloadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformDownloadReq.Marshal(b, m, deterministic)
}
func (dst *PlatformDownloadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformDownloadReq.Merge(dst, src)
}
func (m *PlatformDownloadReq) XXX_Size() int {
	return xxx_messageInfo_PlatformDownloadReq.Size(m)
}
func (m *PlatformDownloadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformDownloadReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformDownloadReq proto.InternalMessageInfo

func (m *PlatformDownloadReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *PlatformDownloadReq) GetPlatformPackage() string {
	if m != nil {
		return m.PlatformPackage
	}
	return ""
}

func (m *PlatformDownloadReq) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *PlatformDownloadReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PlatformDownloadResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlatformDownloadResp) Reset()         { *m = PlatformDownloadResp{} }
func (m *PlatformDownloadResp) String() string { return proto.CompactTextString(m) }
func (*PlatformDownloadResp) ProtoMessage()    {}
func (*PlatformDownloadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_95af83e17996f70c, []int{3}
}
func (m *PlatformDownloadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformDownloadResp.Unmarshal(m, b)
}
func (m *PlatformDownloadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformDownloadResp.Marshal(b, m, deterministic)
}
func (dst *PlatformDownloadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformDownloadResp.Merge(dst, src)
}
func (m *PlatformDownloadResp) XXX_Size() int {
	return xxx_messageInfo_PlatformDownloadResp.Size(m)
}
func (m *PlatformDownloadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformDownloadResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformDownloadResp proto.InternalMessageInfo

func (m *PlatformDownloadResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

type PlatformUninstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	PlatformPackage      string    `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage,proto3" json:"platform_package,omitempty"`
	Architecture         string    `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Version              string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlatformUninstallReq) Reset()         { *m = PlatformUninstallReq{} }
func (m *PlatformUninstallReq) String() string { return proto.CompactTextString(m) }
func (*PlatformUninstallReq) ProtoMessage()    {}
func (*PlatformUninstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_95af83e17996f70c, []int{4}
}
func (m *PlatformUninstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformUninstallReq.Unmarshal(m, b)
}
func (m *PlatformUninstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformUninstallReq.Marshal(b, m, deterministic)
}
func (dst *PlatformUninstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformUninstallReq.Merge(dst, src)
}
func (m *PlatformUninstallReq) XXX_Size() int {
	return xxx_messageInfo_PlatformUninstallReq.Size(m)
}
func (m *PlatformUninstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformUninstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformUninstallReq proto.InternalMessageInfo

func (m *PlatformUninstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *PlatformUninstallReq) GetPlatformPackage() string {
	if m != nil {
		return m.PlatformPackage
	}
	return ""
}

func (m *PlatformUninstallReq) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *PlatformUninstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PlatformUninstallResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatformUninstallResp) Reset()         { *m = PlatformUninstallResp{} }
func (m *PlatformUninstallResp) String() string { return proto.CompactTextString(m) }
func (*PlatformUninstallResp) ProtoMessage()    {}
func (*PlatformUninstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_95af83e17996f70c, []int{5}
}
func (m *PlatformUninstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformUninstallResp.Unmarshal(m, b)
}
func (m *PlatformUninstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformUninstallResp.Marshal(b, m, deterministic)
}
func (dst *PlatformUninstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformUninstallResp.Merge(dst, src)
}
func (m *PlatformUninstallResp) XXX_Size() int {
	return xxx_messageInfo_PlatformUninstallResp.Size(m)
}
func (m *PlatformUninstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformUninstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformUninstallResp proto.InternalMessageInfo

type DownloadProgress struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	TotalSize            int64    `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Downloaded           int64    `protobuf:"varint,4,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Completed            bool     `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadProgress) Reset()         { *m = DownloadProgress{} }
func (m *DownloadProgress) String() string { return proto.CompactTextString(m) }
func (*DownloadProgress) ProtoMessage()    {}
func (*DownloadProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_95af83e17996f70c, []int{6}
}
func (m *DownloadProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadProgress.Unmarshal(m, b)
}
func (m *DownloadProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadProgress.Marshal(b, m, deterministic)
}
func (dst *DownloadProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadProgress.Merge(dst, src)
}
func (m *DownloadProgress) XXX_Size() int {
	return xxx_messageInfo_DownloadProgress.Size(m)
}
func (m *DownloadProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadProgress.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadProgress proto.InternalMessageInfo

func (m *DownloadProgress) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DownloadProgress) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *DownloadProgress) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *DownloadProgress) GetDownloaded() int64 {
	if m != nil {
		return m.Downloaded
	}
	return 0
}

func (m *DownloadProgress) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type PlatformUpgradeReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	PlatformPackage      string    `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage,proto3" json:"platform_package,omitempty"`
	Architecture         string    `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Version              string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlatformUpgradeReq) Reset()         { *m = PlatformUpgradeReq{} }
func (m *PlatformUpgradeReq) String() string { return proto.CompactTextString(m) }
func (*PlatformUpgradeReq) ProtoMessage()    {}
func (*PlatformUpgradeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_95af83e17996f70c, []int{7}
}
func (m *PlatformUpgradeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformUpgradeReq.Unmarshal(m, b)
}
func (m *PlatformUpgradeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformUpgradeReq.Marshal(b, m, deterministic)
}
func (dst *PlatformUpgradeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformUpgradeReq.Merge(dst, src)
}
func (m *PlatformUpgradeReq) XXX_Size() int {
	return xxx_messageInfo_PlatformUpgradeReq.Size(m)
}
func (m *PlatformUpgradeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformUpgradeReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformUpgradeReq proto.InternalMessageInfo

func (m *PlatformUpgradeReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *PlatformUpgradeReq) GetPlatformPackage() string {
	if m != nil {
		return m.PlatformPackage
	}
	return ""
}

func (m *PlatformUpgradeReq) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *PlatformUpgradeReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PlatformUpgradeResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlatformUpgradeResp) Reset()         { *m = PlatformUpgradeResp{} }
func (m *PlatformUpgradeResp) String() string { return proto.CompactTextString(m) }
func (*PlatformUpgradeResp) ProtoMessage()    {}
func (*PlatformUpgradeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_95af83e17996f70c, []int{8}
}
func (m *PlatformUpgradeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformUpgradeResp.Unmarshal(m, b)
}
func (m *PlatformUpgradeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformUpgradeResp.Marshal(b, m, deterministic)
}
func (dst *PlatformUpgradeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformUpgradeResp.Merge(dst, src)
}
func (m *PlatformUpgradeResp) XXX_Size() int {
	return xxx_messageInfo_PlatformUpgradeResp.Size(m)
}
func (m *PlatformUpgradeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformUpgradeResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformUpgradeResp proto.InternalMessageInfo

func (m *PlatformUpgradeResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func init() {
	proto.RegisterType((*PlatformInstallReq)(nil), "arduino.PlatformInstallReq")
	proto.RegisterType((*PlatformInstallResp)(nil), "arduino.PlatformInstallResp")
	proto.RegisterType((*PlatformDownloadReq)(nil), "arduino.PlatformDownloadReq")
	proto.RegisterType((*PlatformDownloadResp)(nil), "arduino.PlatformDownloadResp")
	proto.RegisterType((*PlatformUninstallReq)(nil), "arduino.PlatformUninstallReq")
	proto.RegisterType((*PlatformUninstallResp)(nil), "arduino.PlatformUninstallResp")
	proto.RegisterType((*DownloadProgress)(nil), "arduino.DownloadProgress")
	proto.RegisterType((*PlatformUpgradeReq)(nil), "arduino.PlatformUpgradeReq")
	proto.RegisterType((*PlatformUpgradeResp)(nil), "arduino.PlatformUpgradeResp")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_core_95af83e17996f70c) }

var fileDescriptor_core_95af83e17996f70c = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x54, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x54, 0x5e, 0xfa, 0x5e, 0x9b, 0x7d, 0x95, 0x28, 0x06, 0x44, 0x40, 0x80, 0x50, 0xc4, 0x01,
	0x0e, 0x4d, 0x25, 0x10, 0x3f, 0x80, 0xb8, 0x54, 0x02, 0xa9, 0x32, 0xea, 0x85, 0x4b, 0x95, 0x3a,
	0x6e, 0x6a, 0xe1, 0xc6, 0xc6, 0x71, 0x40, 0xe2, 0x3f, 0xf8, 0x0b, 0xe0, 0x1b, 0x71, 0x53, 0x27,
	0xa5, 0x94, 0x53, 0x4f, 0xe5, 0x14, 0xef, 0xec, 0xec, 0x68, 0x26, 0xc9, 0x1a, 0x80, 0x08, 0x45,
	0x43, 0xa9, 0x84, 0x16, 0xa8, 0x1e, 0xa9, 0x38, 0x67, 0xa9, 0xd8, 0x6f, 0x12, 0x31, 0x99, 0x88,
	0x74, 0x06, 0x07, 0x6f, 0x0e, 0xa0, 0x1e, 0x8f, 0xf4, 0x48, 0xa8, 0x49, 0x37, 0xcd, 0x74, 0xc4,
	0x39, 0xa6, 0x8f, 0xa8, 0x0d, 0x0d, 0x36, 0xad, 0x52, 0x42, 0x7d, 0xe7, 0xd8, 0x39, 0xfd, 0x7f,
	0xbe, 0x19, 0x5a, 0x81, 0xb0, 0x6b, 0x1b, 0xb8, 0xa2, 0xa0, 0x33, 0x68, 0x49, 0x2b, 0x32, 0x90,
	0x11, 0x79, 0x88, 0x12, 0xea, 0xff, 0x31, 0x63, 0x1e, 0xde, 0x28, 0xf1, 0xde, 0x0c, 0x46, 0x01,
	0x34, 0x23, 0x45, 0xc6, 0x4c, 0x53, 0xa2, 0x73, 0x45, 0x7d, 0xb7, 0xa0, 0x2d, 0x60, 0xc8, 0x87,
	0xfa, 0x13, 0x55, 0x19, 0x13, 0xa9, 0x5f, 0x2b, 0xda, 0x65, 0x19, 0xdc, 0xc0, 0xd6, 0x92, 0xdb,
	0x4c, 0xa2, 0x4b, 0x68, 0x98, 0x38, 0x89, 0xa2, 0x59, 0x66, 0xed, 0xee, 0x55, 0x76, 0xaf, 0xc5,
	0x73, 0xca, 0x45, 0x14, 0xf7, 0x2c, 0x01, 0x57, 0xd4, 0xe0, 0xdd, 0x99, 0xcb, 0x95, 0xb4, 0x75,
	0x4e, 0x7f, 0x0b, 0xdb, 0xcb, 0x76, 0x57, 0x8f, 0xff, 0xe1, 0xcc, 0xf5, 0xfa, 0x29, 0x5b, 0xff,
	0xaf, 0xbf, 0x0b, 0x3b, 0x3f, 0xf8, 0xcd, 0x64, 0xf0, 0xea, 0x40, 0xeb, 0x7b, 0x50, 0xd4, 0x02,
	0x37, 0x57, 0xbc, 0x08, 0xe0, 0xe1, 0xe9, 0x11, 0x21, 0xa8, 0x8d, 0x18, 0x2f, 0xcd, 0x15, 0x67,
	0x74, 0x08, 0xa0, 0x85, 0x11, 0x1a, 0x64, 0xec, 0x65, 0xe6, 0xc7, 0xc5, 0x5e, 0x81, 0xdc, 0x19,
	0x00, 0x1d, 0x01, 0xc4, 0x56, 0x98, 0xc6, 0x85, 0x1f, 0x17, 0x7f, 0x41, 0xd0, 0x01, 0x78, 0x66,
	0x9f, 0x24, 0xa7, 0xda, 0xb4, 0xff, 0x9a, 0x76, 0x03, 0xcf, 0x81, 0x85, 0xed, 0xea, 0xcb, 0x44,
	0x99, 0x91, 0x5f, 0xb2, 0x5d, 0x95, 0xdb, 0x95, 0x7f, 0xaf, 0xab, 0x93, 0xfb, 0x20, 0x61, 0x7a,
	0x9c, 0x0f, 0x43, 0xf3, 0x42, 0x3a, 0x76, 0xa0, 0x7c, 0xb6, 0x09, 0x67, 0x1d, 0x25, 0xc9, 0xf0,
	0x5f, 0x71, 0x0f, 0x5d, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xeb, 0x85, 0x53, 0xac, 0x04,
	0x00, 0x00,
}
