// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib.proto

package rpc // import "github.com/arduino/arduino-cli/rpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LibraryDownloadReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryDownloadReq) Reset()         { *m = LibraryDownloadReq{} }
func (m *LibraryDownloadReq) String() string { return proto.CompactTextString(m) }
func (*LibraryDownloadReq) ProtoMessage()    {}
func (*LibraryDownloadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_lib_12805312db4ee020, []int{0}
}
func (m *LibraryDownloadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDownloadReq.Unmarshal(m, b)
}
func (m *LibraryDownloadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDownloadReq.Marshal(b, m, deterministic)
}
func (dst *LibraryDownloadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDownloadReq.Merge(dst, src)
}
func (m *LibraryDownloadReq) XXX_Size() int {
	return xxx_messageInfo_LibraryDownloadReq.Size(m)
}
func (m *LibraryDownloadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDownloadReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDownloadReq proto.InternalMessageInfo

func (m *LibraryDownloadReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryDownloadReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryDownloadReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryDownloadResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LibraryDownloadResp) Reset()         { *m = LibraryDownloadResp{} }
func (m *LibraryDownloadResp) String() string { return proto.CompactTextString(m) }
func (*LibraryDownloadResp) ProtoMessage()    {}
func (*LibraryDownloadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_lib_12805312db4ee020, []int{1}
}
func (m *LibraryDownloadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDownloadResp.Unmarshal(m, b)
}
func (m *LibraryDownloadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDownloadResp.Marshal(b, m, deterministic)
}
func (dst *LibraryDownloadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDownloadResp.Merge(dst, src)
}
func (m *LibraryDownloadResp) XXX_Size() int {
	return xxx_messageInfo_LibraryDownloadResp.Size(m)
}
func (m *LibraryDownloadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDownloadResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDownloadResp proto.InternalMessageInfo

func (m *LibraryDownloadResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

type LibraryInstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryInstallReq) Reset()         { *m = LibraryInstallReq{} }
func (m *LibraryInstallReq) String() string { return proto.CompactTextString(m) }
func (*LibraryInstallReq) ProtoMessage()    {}
func (*LibraryInstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_lib_12805312db4ee020, []int{2}
}
func (m *LibraryInstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryInstallReq.Unmarshal(m, b)
}
func (m *LibraryInstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryInstallReq.Marshal(b, m, deterministic)
}
func (dst *LibraryInstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryInstallReq.Merge(dst, src)
}
func (m *LibraryInstallReq) XXX_Size() int {
	return xxx_messageInfo_LibraryInstallReq.Size(m)
}
func (m *LibraryInstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryInstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryInstallReq proto.InternalMessageInfo

func (m *LibraryInstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryInstallReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryInstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryInstallResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	TaskProgress         *TaskProgress     `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LibraryInstallResp) Reset()         { *m = LibraryInstallResp{} }
func (m *LibraryInstallResp) String() string { return proto.CompactTextString(m) }
func (*LibraryInstallResp) ProtoMessage()    {}
func (*LibraryInstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_lib_12805312db4ee020, []int{3}
}
func (m *LibraryInstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryInstallResp.Unmarshal(m, b)
}
func (m *LibraryInstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryInstallResp.Marshal(b, m, deterministic)
}
func (dst *LibraryInstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryInstallResp.Merge(dst, src)
}
func (m *LibraryInstallResp) XXX_Size() int {
	return xxx_messageInfo_LibraryInstallResp.Size(m)
}
func (m *LibraryInstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryInstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryInstallResp proto.InternalMessageInfo

func (m *LibraryInstallResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *LibraryInstallResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type LibraryUninstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryUninstallReq) Reset()         { *m = LibraryUninstallReq{} }
func (m *LibraryUninstallReq) String() string { return proto.CompactTextString(m) }
func (*LibraryUninstallReq) ProtoMessage()    {}
func (*LibraryUninstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_lib_12805312db4ee020, []int{4}
}
func (m *LibraryUninstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUninstallReq.Unmarshal(m, b)
}
func (m *LibraryUninstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUninstallReq.Marshal(b, m, deterministic)
}
func (dst *LibraryUninstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUninstallReq.Merge(dst, src)
}
func (m *LibraryUninstallReq) XXX_Size() int {
	return xxx_messageInfo_LibraryUninstallReq.Size(m)
}
func (m *LibraryUninstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUninstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUninstallReq proto.InternalMessageInfo

func (m *LibraryUninstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryUninstallReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryUninstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryUninstallResp struct {
	TaskProgress         *TaskProgress `protobuf:"bytes,1,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LibraryUninstallResp) Reset()         { *m = LibraryUninstallResp{} }
func (m *LibraryUninstallResp) String() string { return proto.CompactTextString(m) }
func (*LibraryUninstallResp) ProtoMessage()    {}
func (*LibraryUninstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_lib_12805312db4ee020, []int{5}
}
func (m *LibraryUninstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUninstallResp.Unmarshal(m, b)
}
func (m *LibraryUninstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUninstallResp.Marshal(b, m, deterministic)
}
func (dst *LibraryUninstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUninstallResp.Merge(dst, src)
}
func (m *LibraryUninstallResp) XXX_Size() int {
	return xxx_messageInfo_LibraryUninstallResp.Size(m)
}
func (m *LibraryUninstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUninstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUninstallResp proto.InternalMessageInfo

func (m *LibraryUninstallResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

func init() {
	proto.RegisterType((*LibraryDownloadReq)(nil), "arduino.LibraryDownloadReq")
	proto.RegisterType((*LibraryDownloadResp)(nil), "arduino.LibraryDownloadResp")
	proto.RegisterType((*LibraryInstallReq)(nil), "arduino.LibraryInstallReq")
	proto.RegisterType((*LibraryInstallResp)(nil), "arduino.LibraryInstallResp")
	proto.RegisterType((*LibraryUninstallReq)(nil), "arduino.LibraryUninstallReq")
	proto.RegisterType((*LibraryUninstallResp)(nil), "arduino.LibraryUninstallResp")
}

func init() { proto.RegisterFile("lib.proto", fileDescriptor_lib_12805312db4ee020) }

var fileDescriptor_lib_12805312db4ee020 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xc9, 0x4c, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2c, 0x4a, 0x29, 0xcd, 0xcc, 0xcb, 0x97, 0xe2,
	0x49, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x08, 0x2b, 0x15, 0x72, 0x09, 0xf9, 0x64, 0x26, 0x15,
	0x25, 0x16, 0x55, 0xba, 0xe4, 0x97, 0xe7, 0xe5, 0xe4, 0x27, 0xa6, 0x04, 0xa5, 0x16, 0x0a, 0xe9,
	0x72, 0x71, 0x64, 0xe6, 0x15, 0x97, 0x24, 0xe6, 0x25, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x1b, 0x09, 0xea, 0x41, 0xf5, 0xeb, 0x79, 0x42, 0x25, 0x82, 0xe0, 0x4a, 0x84, 0x84, 0xb8, 0x58,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x80, 0x4a, 0x39, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6,
	0xb2, 0xd4, 0xa2, 0xe2, 0xcc, 0xfc, 0x3c, 0x09, 0x66, 0xb0, 0x30, 0x8c, 0xab, 0xe4, 0xc3, 0x25,
	0x8c, 0x61, 0x65, 0x71, 0x81, 0x90, 0x29, 0x17, 0x07, 0xd0, 0x49, 0xe9, 0x45, 0xa9, 0xc5, 0xc5,
	0x50, 0x3b, 0x25, 0xe1, 0x76, 0xc2, 0x14, 0x06, 0x40, 0x15, 0x04, 0xc1, 0x95, 0x2a, 0x15, 0x70,
	0x09, 0x42, 0x4d, 0x03, 0x3b, 0x2c, 0x27, 0x87, 0xe6, 0xee, 0x6f, 0x67, 0x84, 0x87, 0x19, 0xdc,
	0x4a, 0xb2, 0xdd, 0x2f, 0x64, 0xc5, 0xc5, 0x5b, 0x92, 0x58, 0x9c, 0x1d, 0x0f, 0xd7, 0xcb, 0x04,
	0xd6, 0x2b, 0x0a, 0xd7, 0x1b, 0x02, 0x94, 0x85, 0xeb, 0xe3, 0x29, 0x41, 0xe2, 0x29, 0x15, 0xc1,
	0x43, 0x32, 0x34, 0x2f, 0x93, 0x4e, 0xbe, 0x0f, 0xe2, 0x12, 0xc1, 0xb4, 0x13, 0xe8, 0x7d, 0x0c,
	0x7f, 0x30, 0x12, 0xed, 0x0f, 0x27, 0x95, 0x28, 0xa5, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0x3d,
	0x60, 0xda, 0xd4, 0x87, 0x6a, 0x80, 0xd1, 0xba, 0xc9, 0x39, 0x99, 0xfa, 0x45, 0x05, 0xc9, 0x49,
	0x6c, 0xe0, 0x14, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x71, 0xb7, 0x04, 0xd5, 0x02,
	0x00, 0x00,
}
