// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands/compile.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CompileReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Fqbn                 string    `protobuf:"bytes,2,opt,name=fqbn,proto3" json:"fqbn,omitempty"`
	SketchPath           string    `protobuf:"bytes,3,opt,name=sketchPath,proto3" json:"sketchPath,omitempty"`
	ShowProperties       bool      `protobuf:"varint,4,opt,name=showProperties,proto3" json:"showProperties,omitempty"`
	Preprocess           bool      `protobuf:"varint,5,opt,name=preprocess,proto3" json:"preprocess,omitempty"`
	BuildCachePath       string    `protobuf:"bytes,6,opt,name=buildCachePath,proto3" json:"buildCachePath,omitempty"`
	BuildPath            string    `protobuf:"bytes,7,opt,name=buildPath,proto3" json:"buildPath,omitempty"`
	BuildProperties      []string  `protobuf:"bytes,8,rep,name=buildProperties,proto3" json:"buildProperties,omitempty"`
	Warnings             string    `protobuf:"bytes,9,opt,name=warnings,proto3" json:"warnings,omitempty"`
	Verbose              bool      `protobuf:"varint,10,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Quiet                bool      `protobuf:"varint,11,opt,name=quiet,proto3" json:"quiet,omitempty"`
	VidPid               string    `protobuf:"bytes,12,opt,name=vidPid,proto3" json:"vidPid,omitempty"`
	ExportFile           string    `protobuf:"bytes,13,opt,name=exportFile,proto3" json:"exportFile,omitempty"`
	Jobs                 int32     `protobuf:"varint,14,opt,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CompileReq) Reset()         { *m = CompileReq{} }
func (m *CompileReq) String() string { return proto.CompactTextString(m) }
func (*CompileReq) ProtoMessage()    {}
func (*CompileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86bc582849c76c3d, []int{0}
}

func (m *CompileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompileReq.Unmarshal(m, b)
}
func (m *CompileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompileReq.Marshal(b, m, deterministic)
}
func (m *CompileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompileReq.Merge(m, src)
}
func (m *CompileReq) XXX_Size() int {
	return xxx_messageInfo_CompileReq.Size(m)
}
func (m *CompileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompileReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompileReq proto.InternalMessageInfo

func (m *CompileReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *CompileReq) GetFqbn() string {
	if m != nil {
		return m.Fqbn
	}
	return ""
}

func (m *CompileReq) GetSketchPath() string {
	if m != nil {
		return m.SketchPath
	}
	return ""
}

func (m *CompileReq) GetShowProperties() bool {
	if m != nil {
		return m.ShowProperties
	}
	return false
}

func (m *CompileReq) GetPreprocess() bool {
	if m != nil {
		return m.Preprocess
	}
	return false
}

func (m *CompileReq) GetBuildCachePath() string {
	if m != nil {
		return m.BuildCachePath
	}
	return ""
}

func (m *CompileReq) GetBuildPath() string {
	if m != nil {
		return m.BuildPath
	}
	return ""
}

func (m *CompileReq) GetBuildProperties() []string {
	if m != nil {
		return m.BuildProperties
	}
	return nil
}

func (m *CompileReq) GetWarnings() string {
	if m != nil {
		return m.Warnings
	}
	return ""
}

func (m *CompileReq) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func (m *CompileReq) GetQuiet() bool {
	if m != nil {
		return m.Quiet
	}
	return false
}

func (m *CompileReq) GetVidPid() string {
	if m != nil {
		return m.VidPid
	}
	return ""
}

func (m *CompileReq) GetExportFile() string {
	if m != nil {
		return m.ExportFile
	}
	return ""
}

func (m *CompileReq) GetJobs() int32 {
	if m != nil {
		return m.Jobs
	}
	return 0
}

type CompileResp struct {
	OutStream            []byte   `protobuf:"bytes,1,opt,name=out_stream,json=outStream,proto3" json:"out_stream,omitempty"`
	ErrStream            []byte   `protobuf:"bytes,2,opt,name=err_stream,json=errStream,proto3" json:"err_stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompileResp) Reset()         { *m = CompileResp{} }
func (m *CompileResp) String() string { return proto.CompactTextString(m) }
func (*CompileResp) ProtoMessage()    {}
func (*CompileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_86bc582849c76c3d, []int{1}
}

func (m *CompileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompileResp.Unmarshal(m, b)
}
func (m *CompileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompileResp.Marshal(b, m, deterministic)
}
func (m *CompileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompileResp.Merge(m, src)
}
func (m *CompileResp) XXX_Size() int {
	return xxx_messageInfo_CompileResp.Size(m)
}
func (m *CompileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CompileResp.DiscardUnknown(m)
}

var xxx_messageInfo_CompileResp proto.InternalMessageInfo

func (m *CompileResp) GetOutStream() []byte {
	if m != nil {
		return m.OutStream
	}
	return nil
}

func (m *CompileResp) GetErrStream() []byte {
	if m != nil {
		return m.ErrStream
	}
	return nil
}

func init() {
	proto.RegisterType((*CompileReq)(nil), "cc.arduino.cli.commands.CompileReq")
	proto.RegisterType((*CompileResp)(nil), "cc.arduino.cli.commands.CompileResp")
}

func init() { proto.RegisterFile("commands/compile.proto", fileDescriptor_86bc582849c76c3d) }

var fileDescriptor_86bc582849c76c3d = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x8f, 0xd3, 0x30,
	0x10, 0x85, 0x95, 0xed, 0xb6, 0x9b, 0x4c, 0x97, 0x45, 0xb2, 0x60, 0xb1, 0x2a, 0x40, 0xa1, 0x07,
	0x14, 0x09, 0x35, 0x91, 0xe0, 0xcc, 0x85, 0x4a, 0x48, 0x88, 0x4b, 0x15, 0x6e, 0x5c, 0x50, 0xe2,
	0x0c, 0x8d, 0x21, 0xb1, 0x5d, 0xdb, 0x69, 0xf9, 0x97, 0xfc, 0x25, 0x94, 0x49, 0xd3, 0x56, 0x95,
	0x38, 0xc5, 0xf3, 0xbd, 0xe7, 0x67, 0xc7, 0x33, 0xf0, 0x28, 0x74, 0xdb, 0x16, 0xaa, 0x72, 0x99,
	0xd0, 0xad, 0x91, 0x0d, 0xa6, 0xc6, 0x6a, 0xaf, 0xd9, 0x0b, 0x21, 0xd2, 0xc2, 0x56, 0x9d, 0x54,
	0x3a, 0x15, 0x8d, 0x4c, 0x47, 0xdb, 0xe2, 0xf9, 0xe5, 0x86, 0x56, 0xab, 0xc1, 0xbf, 0xfc, 0x3b,
	0x01, 0x58, 0x0f, 0x09, 0x39, 0xee, 0xd8, 0x47, 0x08, 0xa5, 0x72, 0xbe, 0x50, 0x02, 0x79, 0x10,
	0x07, 0xc9, 0xfc, 0xfd, 0x9b, 0xf4, 0x3f, 0x89, 0xe9, 0x97, 0xa3, 0x31, 0x3f, 0x6d, 0x61, 0x0c,
	0x6e, 0x7f, 0xee, 0x4a, 0xc5, 0x6f, 0xe2, 0x20, 0x89, 0x72, 0x5a, 0xb3, 0xd7, 0x00, 0xee, 0x37,
	0x7a, 0x51, 0x6f, 0x0a, 0x5f, 0xf3, 0x09, 0x29, 0x17, 0x84, 0xbd, 0x85, 0x07, 0x57, 0xeb, 0xc3,
	0xc6, 0x6a, 0x83, 0xd6, 0x4b, 0x74, 0xfc, 0x36, 0x0e, 0x92, 0x30, 0xbf, 0xa2, 0x7d, 0x8e, 0xb1,
	0x68, 0xac, 0x16, 0xe8, 0x1c, 0x9f, 0x92, 0xe7, 0x82, 0xf4, 0x39, 0x65, 0x27, 0x9b, 0x6a, 0x5d,
	0x88, 0x1a, 0xe9, 0xac, 0x19, 0x9d, 0x75, 0x45, 0xd9, 0x4b, 0x88, 0x88, 0x90, 0xe5, 0x8e, 0x2c,
	0x67, 0xc0, 0x12, 0x78, 0x3a, 0x14, 0xe7, 0xeb, 0x84, 0xf1, 0x24, 0x89, 0xf2, 0x6b, 0xcc, 0x16,
	0x10, 0x1e, 0x0a, 0xab, 0xa4, 0xda, 0x3a, 0x1e, 0x51, 0xcc, 0xa9, 0x66, 0x1c, 0xee, 0xf6, 0x68,
	0x4b, 0xed, 0x90, 0x03, 0x5d, 0x74, 0x2c, 0xd9, 0x33, 0x98, 0xee, 0x3a, 0x89, 0x9e, 0xcf, 0x89,
	0x0f, 0x05, 0x7b, 0x84, 0xd9, 0x5e, 0x56, 0x1b, 0x59, 0xf1, 0x7b, 0x4a, 0x3a, 0x56, 0xfd, 0x3f,
	0xe3, 0x1f, 0xa3, 0xad, 0xff, 0x2c, 0x1b, 0xe4, 0x4f, 0x86, 0xb7, 0x3b, 0x93, 0xfe, 0xbd, 0x7f,
	0xe9, 0xd2, 0xf1, 0x87, 0x38, 0x48, 0xa6, 0x39, 0xad, 0x97, 0x5f, 0x61, 0x7e, 0x6a, 0xa8, 0x33,
	0xec, 0x15, 0x80, 0xee, 0xfc, 0x0f, 0xe7, 0x2d, 0x16, 0x2d, 0xf5, 0xf4, 0x3e, 0x8f, 0x74, 0xe7,
	0xbf, 0x11, 0xe8, 0x65, 0xb4, 0x76, 0x94, 0x6f, 0x06, 0x19, 0xad, 0x1d, 0xe4, 0x4f, 0xab, 0xef,
	0xef, 0xb6, 0xd2, 0xd7, 0x5d, 0xd9, 0xb7, 0x3d, 0x3b, 0x8e, 0xc1, 0xf8, 0x5d, 0x89, 0x46, 0x66,
	0xd6, 0x88, 0x6c, 0x1c, 0x89, 0x72, 0x46, 0x43, 0xf5, 0xe1, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x14, 0x81, 0xb3, 0x02, 0x9e, 0x02, 0x00, 0x00,
}
