// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands/lib.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LibraryLayout int32

const (
	LibraryLayout_flat_layout      LibraryLayout = 0
	LibraryLayout_recursive_layout LibraryLayout = 1
)

var LibraryLayout_name = map[int32]string{
	0: "flat_layout",
	1: "recursive_layout",
}

var LibraryLayout_value = map[string]int32{
	"flat_layout":      0,
	"recursive_layout": 1,
}

func (x LibraryLayout) String() string {
	return proto.EnumName(LibraryLayout_name, int32(x))
}

func (LibraryLayout) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{0}
}

type LibraryLocation int32

const (
	LibraryLocation_ide_builtin                 LibraryLocation = 0
	LibraryLocation_platform_builtin            LibraryLocation = 1
	LibraryLocation_referenced_platform_builtin LibraryLocation = 2
	LibraryLocation_sketchbook                  LibraryLocation = 3
)

var LibraryLocation_name = map[int32]string{
	0: "ide_builtin",
	1: "platform_builtin",
	2: "referenced_platform_builtin",
	3: "sketchbook",
}

var LibraryLocation_value = map[string]int32{
	"ide_builtin":                 0,
	"platform_builtin":            1,
	"referenced_platform_builtin": 2,
	"sketchbook":                  3,
}

func (x LibraryLocation) String() string {
	return proto.EnumName(LibraryLocation_name, int32(x))
}

func (LibraryLocation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{1}
}

type LibraryDownloadReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryDownloadReq) Reset()         { *m = LibraryDownloadReq{} }
func (m *LibraryDownloadReq) String() string { return proto.CompactTextString(m) }
func (*LibraryDownloadReq) ProtoMessage()    {}
func (*LibraryDownloadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{0}
}

func (m *LibraryDownloadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDownloadReq.Unmarshal(m, b)
}
func (m *LibraryDownloadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDownloadReq.Marshal(b, m, deterministic)
}
func (m *LibraryDownloadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDownloadReq.Merge(m, src)
}
func (m *LibraryDownloadReq) XXX_Size() int {
	return xxx_messageInfo_LibraryDownloadReq.Size(m)
}
func (m *LibraryDownloadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDownloadReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDownloadReq proto.InternalMessageInfo

func (m *LibraryDownloadReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryDownloadReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryDownloadReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryDownloadResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LibraryDownloadResp) Reset()         { *m = LibraryDownloadResp{} }
func (m *LibraryDownloadResp) String() string { return proto.CompactTextString(m) }
func (*LibraryDownloadResp) ProtoMessage()    {}
func (*LibraryDownloadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{1}
}

func (m *LibraryDownloadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDownloadResp.Unmarshal(m, b)
}
func (m *LibraryDownloadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDownloadResp.Marshal(b, m, deterministic)
}
func (m *LibraryDownloadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDownloadResp.Merge(m, src)
}
func (m *LibraryDownloadResp) XXX_Size() int {
	return xxx_messageInfo_LibraryDownloadResp.Size(m)
}
func (m *LibraryDownloadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDownloadResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDownloadResp proto.InternalMessageInfo

func (m *LibraryDownloadResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

type LibraryInstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryInstallReq) Reset()         { *m = LibraryInstallReq{} }
func (m *LibraryInstallReq) String() string { return proto.CompactTextString(m) }
func (*LibraryInstallReq) ProtoMessage()    {}
func (*LibraryInstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{2}
}

func (m *LibraryInstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryInstallReq.Unmarshal(m, b)
}
func (m *LibraryInstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryInstallReq.Marshal(b, m, deterministic)
}
func (m *LibraryInstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryInstallReq.Merge(m, src)
}
func (m *LibraryInstallReq) XXX_Size() int {
	return xxx_messageInfo_LibraryInstallReq.Size(m)
}
func (m *LibraryInstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryInstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryInstallReq proto.InternalMessageInfo

func (m *LibraryInstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryInstallReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryInstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryInstallResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	TaskProgress         *TaskProgress     `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LibraryInstallResp) Reset()         { *m = LibraryInstallResp{} }
func (m *LibraryInstallResp) String() string { return proto.CompactTextString(m) }
func (*LibraryInstallResp) ProtoMessage()    {}
func (*LibraryInstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{3}
}

func (m *LibraryInstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryInstallResp.Unmarshal(m, b)
}
func (m *LibraryInstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryInstallResp.Marshal(b, m, deterministic)
}
func (m *LibraryInstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryInstallResp.Merge(m, src)
}
func (m *LibraryInstallResp) XXX_Size() int {
	return xxx_messageInfo_LibraryInstallResp.Size(m)
}
func (m *LibraryInstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryInstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryInstallResp proto.InternalMessageInfo

func (m *LibraryInstallResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *LibraryInstallResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type LibraryUninstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryUninstallReq) Reset()         { *m = LibraryUninstallReq{} }
func (m *LibraryUninstallReq) String() string { return proto.CompactTextString(m) }
func (*LibraryUninstallReq) ProtoMessage()    {}
func (*LibraryUninstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{4}
}

func (m *LibraryUninstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUninstallReq.Unmarshal(m, b)
}
func (m *LibraryUninstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUninstallReq.Marshal(b, m, deterministic)
}
func (m *LibraryUninstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUninstallReq.Merge(m, src)
}
func (m *LibraryUninstallReq) XXX_Size() int {
	return xxx_messageInfo_LibraryUninstallReq.Size(m)
}
func (m *LibraryUninstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUninstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUninstallReq proto.InternalMessageInfo

func (m *LibraryUninstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryUninstallReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryUninstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryUninstallResp struct {
	TaskProgress         *TaskProgress `protobuf:"bytes,1,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LibraryUninstallResp) Reset()         { *m = LibraryUninstallResp{} }
func (m *LibraryUninstallResp) String() string { return proto.CompactTextString(m) }
func (*LibraryUninstallResp) ProtoMessage()    {}
func (*LibraryUninstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{5}
}

func (m *LibraryUninstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUninstallResp.Unmarshal(m, b)
}
func (m *LibraryUninstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUninstallResp.Marshal(b, m, deterministic)
}
func (m *LibraryUninstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUninstallResp.Merge(m, src)
}
func (m *LibraryUninstallResp) XXX_Size() int {
	return xxx_messageInfo_LibraryUninstallResp.Size(m)
}
func (m *LibraryUninstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUninstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUninstallResp proto.InternalMessageInfo

func (m *LibraryUninstallResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type LibraryUpgradeAllReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryUpgradeAllReq) Reset()         { *m = LibraryUpgradeAllReq{} }
func (m *LibraryUpgradeAllReq) String() string { return proto.CompactTextString(m) }
func (*LibraryUpgradeAllReq) ProtoMessage()    {}
func (*LibraryUpgradeAllReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{6}
}

func (m *LibraryUpgradeAllReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUpgradeAllReq.Unmarshal(m, b)
}
func (m *LibraryUpgradeAllReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUpgradeAllReq.Marshal(b, m, deterministic)
}
func (m *LibraryUpgradeAllReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUpgradeAllReq.Merge(m, src)
}
func (m *LibraryUpgradeAllReq) XXX_Size() int {
	return xxx_messageInfo_LibraryUpgradeAllReq.Size(m)
}
func (m *LibraryUpgradeAllReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUpgradeAllReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUpgradeAllReq proto.InternalMessageInfo

func (m *LibraryUpgradeAllReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

type LibraryUpgradeAllResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	TaskProgress         *TaskProgress     `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LibraryUpgradeAllResp) Reset()         { *m = LibraryUpgradeAllResp{} }
func (m *LibraryUpgradeAllResp) String() string { return proto.CompactTextString(m) }
func (*LibraryUpgradeAllResp) ProtoMessage()    {}
func (*LibraryUpgradeAllResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{7}
}

func (m *LibraryUpgradeAllResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUpgradeAllResp.Unmarshal(m, b)
}
func (m *LibraryUpgradeAllResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUpgradeAllResp.Marshal(b, m, deterministic)
}
func (m *LibraryUpgradeAllResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUpgradeAllResp.Merge(m, src)
}
func (m *LibraryUpgradeAllResp) XXX_Size() int {
	return xxx_messageInfo_LibraryUpgradeAllResp.Size(m)
}
func (m *LibraryUpgradeAllResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUpgradeAllResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUpgradeAllResp proto.InternalMessageInfo

func (m *LibraryUpgradeAllResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *LibraryUpgradeAllResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type LibraryResolveDependenciesReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryResolveDependenciesReq) Reset()         { *m = LibraryResolveDependenciesReq{} }
func (m *LibraryResolveDependenciesReq) String() string { return proto.CompactTextString(m) }
func (*LibraryResolveDependenciesReq) ProtoMessage()    {}
func (*LibraryResolveDependenciesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{8}
}

func (m *LibraryResolveDependenciesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryResolveDependenciesReq.Unmarshal(m, b)
}
func (m *LibraryResolveDependenciesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryResolveDependenciesReq.Marshal(b, m, deterministic)
}
func (m *LibraryResolveDependenciesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryResolveDependenciesReq.Merge(m, src)
}
func (m *LibraryResolveDependenciesReq) XXX_Size() int {
	return xxx_messageInfo_LibraryResolveDependenciesReq.Size(m)
}
func (m *LibraryResolveDependenciesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryResolveDependenciesReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryResolveDependenciesReq proto.InternalMessageInfo

func (m *LibraryResolveDependenciesReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryResolveDependenciesReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryResolveDependenciesReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryResolveDependenciesResp struct {
	Dependencies         []*LibraryDependencyStatus `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *LibraryResolveDependenciesResp) Reset()         { *m = LibraryResolveDependenciesResp{} }
func (m *LibraryResolveDependenciesResp) String() string { return proto.CompactTextString(m) }
func (*LibraryResolveDependenciesResp) ProtoMessage()    {}
func (*LibraryResolveDependenciesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{9}
}

func (m *LibraryResolveDependenciesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryResolveDependenciesResp.Unmarshal(m, b)
}
func (m *LibraryResolveDependenciesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryResolveDependenciesResp.Marshal(b, m, deterministic)
}
func (m *LibraryResolveDependenciesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryResolveDependenciesResp.Merge(m, src)
}
func (m *LibraryResolveDependenciesResp) XXX_Size() int {
	return xxx_messageInfo_LibraryResolveDependenciesResp.Size(m)
}
func (m *LibraryResolveDependenciesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryResolveDependenciesResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryResolveDependenciesResp proto.InternalMessageInfo

func (m *LibraryResolveDependenciesResp) GetDependencies() []*LibraryDependencyStatus {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type LibraryDependencyStatus struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VersionRequired      string   `protobuf:"bytes,2,opt,name=versionRequired,proto3" json:"versionRequired,omitempty"`
	VersionInstalled     string   `protobuf:"bytes,3,opt,name=versionInstalled,proto3" json:"versionInstalled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryDependencyStatus) Reset()         { *m = LibraryDependencyStatus{} }
func (m *LibraryDependencyStatus) String() string { return proto.CompactTextString(m) }
func (*LibraryDependencyStatus) ProtoMessage()    {}
func (*LibraryDependencyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{10}
}

func (m *LibraryDependencyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDependencyStatus.Unmarshal(m, b)
}
func (m *LibraryDependencyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDependencyStatus.Marshal(b, m, deterministic)
}
func (m *LibraryDependencyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDependencyStatus.Merge(m, src)
}
func (m *LibraryDependencyStatus) XXX_Size() int {
	return xxx_messageInfo_LibraryDependencyStatus.Size(m)
}
func (m *LibraryDependencyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDependencyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDependencyStatus proto.InternalMessageInfo

func (m *LibraryDependencyStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryDependencyStatus) GetVersionRequired() string {
	if m != nil {
		return m.VersionRequired
	}
	return ""
}

func (m *LibraryDependencyStatus) GetVersionInstalled() string {
	if m != nil {
		return m.VersionInstalled
	}
	return ""
}

type LibrarySearchReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Query                string    `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibrarySearchReq) Reset()         { *m = LibrarySearchReq{} }
func (m *LibrarySearchReq) String() string { return proto.CompactTextString(m) }
func (*LibrarySearchReq) ProtoMessage()    {}
func (*LibrarySearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{11}
}

func (m *LibrarySearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibrarySearchReq.Unmarshal(m, b)
}
func (m *LibrarySearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibrarySearchReq.Marshal(b, m, deterministic)
}
func (m *LibrarySearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibrarySearchReq.Merge(m, src)
}
func (m *LibrarySearchReq) XXX_Size() int {
	return xxx_messageInfo_LibrarySearchReq.Size(m)
}
func (m *LibrarySearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibrarySearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibrarySearchReq proto.InternalMessageInfo

func (m *LibrarySearchReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibrarySearchReq) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type LibrarySearchResp struct {
	Libraries            []*SearchedLibrary `protobuf:"bytes,1,rep,name=libraries,proto3" json:"libraries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LibrarySearchResp) Reset()         { *m = LibrarySearchResp{} }
func (m *LibrarySearchResp) String() string { return proto.CompactTextString(m) }
func (*LibrarySearchResp) ProtoMessage()    {}
func (*LibrarySearchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{12}
}

func (m *LibrarySearchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibrarySearchResp.Unmarshal(m, b)
}
func (m *LibrarySearchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibrarySearchResp.Marshal(b, m, deterministic)
}
func (m *LibrarySearchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibrarySearchResp.Merge(m, src)
}
func (m *LibrarySearchResp) XXX_Size() int {
	return xxx_messageInfo_LibrarySearchResp.Size(m)
}
func (m *LibrarySearchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibrarySearchResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibrarySearchResp proto.InternalMessageInfo

func (m *LibrarySearchResp) GetLibraries() []*SearchedLibrary {
	if m != nil {
		return m.Libraries
	}
	return nil
}

type SearchedLibrary struct {
	Name                 string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Releases             map[string]*LibraryRelease `protobuf:"bytes,2,rep,name=releases,proto3" json:"releases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Latest               *LibraryRelease            `protobuf:"bytes,3,opt,name=latest,proto3" json:"latest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SearchedLibrary) Reset()         { *m = SearchedLibrary{} }
func (m *SearchedLibrary) String() string { return proto.CompactTextString(m) }
func (*SearchedLibrary) ProtoMessage()    {}
func (*SearchedLibrary) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{13}
}

func (m *SearchedLibrary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchedLibrary.Unmarshal(m, b)
}
func (m *SearchedLibrary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchedLibrary.Marshal(b, m, deterministic)
}
func (m *SearchedLibrary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchedLibrary.Merge(m, src)
}
func (m *SearchedLibrary) XXX_Size() int {
	return xxx_messageInfo_SearchedLibrary.Size(m)
}
func (m *SearchedLibrary) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchedLibrary.DiscardUnknown(m)
}

var xxx_messageInfo_SearchedLibrary proto.InternalMessageInfo

func (m *SearchedLibrary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchedLibrary) GetReleases() map[string]*LibraryRelease {
	if m != nil {
		return m.Releases
	}
	return nil
}

func (m *SearchedLibrary) GetLatest() *LibraryRelease {
	if m != nil {
		return m.Latest
	}
	return nil
}

type LibraryRelease struct {
	Author               string               `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Version              string               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Maintainer           string               `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	Sentence             string               `protobuf:"bytes,4,opt,name=sentence,proto3" json:"sentence,omitempty"`
	Paragraph            string               `protobuf:"bytes,5,opt,name=paragraph,proto3" json:"paragraph,omitempty"`
	Website              string               `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	Category             string               `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Architectures        []string             `protobuf:"bytes,8,rep,name=architectures,proto3" json:"architectures,omitempty"`
	Types                []string             `protobuf:"bytes,9,rep,name=types,proto3" json:"types,omitempty"`
	Resources            *DownloadResource    `protobuf:"bytes,10,opt,name=resources,proto3" json:"resources,omitempty"`
	License              string               `protobuf:"bytes,11,opt,name=license,proto3" json:"license,omitempty"`
	ProvidesIncludes     []string             `protobuf:"bytes,12,rep,name=provides_includes,json=providesIncludes,proto3" json:"provides_includes,omitempty"`
	Dependencies         []*LibraryDependency `protobuf:"bytes,13,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LibraryRelease) Reset()         { *m = LibraryRelease{} }
func (m *LibraryRelease) String() string { return proto.CompactTextString(m) }
func (*LibraryRelease) ProtoMessage()    {}
func (*LibraryRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{14}
}

func (m *LibraryRelease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryRelease.Unmarshal(m, b)
}
func (m *LibraryRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryRelease.Marshal(b, m, deterministic)
}
func (m *LibraryRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryRelease.Merge(m, src)
}
func (m *LibraryRelease) XXX_Size() int {
	return xxx_messageInfo_LibraryRelease.Size(m)
}
func (m *LibraryRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryRelease.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryRelease proto.InternalMessageInfo

func (m *LibraryRelease) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *LibraryRelease) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LibraryRelease) GetMaintainer() string {
	if m != nil {
		return m.Maintainer
	}
	return ""
}

func (m *LibraryRelease) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

func (m *LibraryRelease) GetParagraph() string {
	if m != nil {
		return m.Paragraph
	}
	return ""
}

func (m *LibraryRelease) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *LibraryRelease) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *LibraryRelease) GetArchitectures() []string {
	if m != nil {
		return m.Architectures
	}
	return nil
}

func (m *LibraryRelease) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *LibraryRelease) GetResources() *DownloadResource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *LibraryRelease) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

func (m *LibraryRelease) GetProvidesIncludes() []string {
	if m != nil {
		return m.ProvidesIncludes
	}
	return nil
}

func (m *LibraryRelease) GetDependencies() []*LibraryDependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type LibraryDependency struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VersionConstraint    string   `protobuf:"bytes,2,opt,name=version_constraint,json=versionConstraint,proto3" json:"version_constraint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryDependency) Reset()         { *m = LibraryDependency{} }
func (m *LibraryDependency) String() string { return proto.CompactTextString(m) }
func (*LibraryDependency) ProtoMessage()    {}
func (*LibraryDependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{15}
}

func (m *LibraryDependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDependency.Unmarshal(m, b)
}
func (m *LibraryDependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDependency.Marshal(b, m, deterministic)
}
func (m *LibraryDependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDependency.Merge(m, src)
}
func (m *LibraryDependency) XXX_Size() int {
	return xxx_messageInfo_LibraryDependency.Size(m)
}
func (m *LibraryDependency) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDependency.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDependency proto.InternalMessageInfo

func (m *LibraryDependency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryDependency) GetVersionConstraint() string {
	if m != nil {
		return m.VersionConstraint
	}
	return ""
}

type DownloadResource struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Archivefilename      string   `protobuf:"bytes,2,opt,name=archivefilename,proto3" json:"archivefilename,omitempty"`
	Checksum             string   `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Cachepath            string   `protobuf:"bytes,5,opt,name=cachepath,proto3" json:"cachepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadResource) Reset()         { *m = DownloadResource{} }
func (m *DownloadResource) String() string { return proto.CompactTextString(m) }
func (*DownloadResource) ProtoMessage()    {}
func (*DownloadResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{16}
}

func (m *DownloadResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadResource.Unmarshal(m, b)
}
func (m *DownloadResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadResource.Marshal(b, m, deterministic)
}
func (m *DownloadResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadResource.Merge(m, src)
}
func (m *DownloadResource) XXX_Size() int {
	return xxx_messageInfo_DownloadResource.Size(m)
}
func (m *DownloadResource) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadResource.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadResource proto.InternalMessageInfo

func (m *DownloadResource) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DownloadResource) GetArchivefilename() string {
	if m != nil {
		return m.Archivefilename
	}
	return ""
}

func (m *DownloadResource) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *DownloadResource) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *DownloadResource) GetCachepath() string {
	if m != nil {
		return m.Cachepath
	}
	return ""
}

type LibraryListReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	All                  bool      `protobuf:"varint,2,opt,name=all,proto3" json:"all,omitempty"`
	Updatable            bool      `protobuf:"varint,3,opt,name=updatable,proto3" json:"updatable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryListReq) Reset()         { *m = LibraryListReq{} }
func (m *LibraryListReq) String() string { return proto.CompactTextString(m) }
func (*LibraryListReq) ProtoMessage()    {}
func (*LibraryListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{17}
}

func (m *LibraryListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryListReq.Unmarshal(m, b)
}
func (m *LibraryListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryListReq.Marshal(b, m, deterministic)
}
func (m *LibraryListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryListReq.Merge(m, src)
}
func (m *LibraryListReq) XXX_Size() int {
	return xxx_messageInfo_LibraryListReq.Size(m)
}
func (m *LibraryListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryListReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryListReq proto.InternalMessageInfo

func (m *LibraryListReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryListReq) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

func (m *LibraryListReq) GetUpdatable() bool {
	if m != nil {
		return m.Updatable
	}
	return false
}

type LibraryListResp struct {
	InstalledLibrary     []*InstalledLibrary `protobuf:"bytes,1,rep,name=installed_library,json=installedLibrary,proto3" json:"installed_library,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LibraryListResp) Reset()         { *m = LibraryListResp{} }
func (m *LibraryListResp) String() string { return proto.CompactTextString(m) }
func (*LibraryListResp) ProtoMessage()    {}
func (*LibraryListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{18}
}

func (m *LibraryListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryListResp.Unmarshal(m, b)
}
func (m *LibraryListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryListResp.Marshal(b, m, deterministic)
}
func (m *LibraryListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryListResp.Merge(m, src)
}
func (m *LibraryListResp) XXX_Size() int {
	return xxx_messageInfo_LibraryListResp.Size(m)
}
func (m *LibraryListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryListResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryListResp proto.InternalMessageInfo

func (m *LibraryListResp) GetInstalledLibrary() []*InstalledLibrary {
	if m != nil {
		return m.InstalledLibrary
	}
	return nil
}

type InstalledLibrary struct {
	Library              *Library        `protobuf:"bytes,1,opt,name=library,proto3" json:"library,omitempty"`
	Release              *LibraryRelease `protobuf:"bytes,2,opt,name=release,proto3" json:"release,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InstalledLibrary) Reset()         { *m = InstalledLibrary{} }
func (m *InstalledLibrary) String() string { return proto.CompactTextString(m) }
func (*InstalledLibrary) ProtoMessage()    {}
func (*InstalledLibrary) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{19}
}

func (m *InstalledLibrary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstalledLibrary.Unmarshal(m, b)
}
func (m *InstalledLibrary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstalledLibrary.Marshal(b, m, deterministic)
}
func (m *InstalledLibrary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstalledLibrary.Merge(m, src)
}
func (m *InstalledLibrary) XXX_Size() int {
	return xxx_messageInfo_InstalledLibrary.Size(m)
}
func (m *InstalledLibrary) XXX_DiscardUnknown() {
	xxx_messageInfo_InstalledLibrary.DiscardUnknown(m)
}

var xxx_messageInfo_InstalledLibrary proto.InternalMessageInfo

func (m *InstalledLibrary) GetLibrary() *Library {
	if m != nil {
		return m.Library
	}
	return nil
}

func (m *InstalledLibrary) GetRelease() *LibraryRelease {
	if m != nil {
		return m.Release
	}
	return nil
}

type Library struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author               string            `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Maintainer           string            `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	Sentence             string            `protobuf:"bytes,4,opt,name=sentence,proto3" json:"sentence,omitempty"`
	Paragraph            string            `protobuf:"bytes,5,opt,name=paragraph,proto3" json:"paragraph,omitempty"`
	Website              string            `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	Category             string            `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Architectures        []string          `protobuf:"bytes,8,rep,name=architectures,proto3" json:"architectures,omitempty"`
	Types                []string          `protobuf:"bytes,9,rep,name=types,proto3" json:"types,omitempty"`
	InstallDir           string            `protobuf:"bytes,10,opt,name=install_dir,json=installDir,proto3" json:"install_dir,omitempty"`
	SourceDir            string            `protobuf:"bytes,11,opt,name=source_dir,json=sourceDir,proto3" json:"source_dir,omitempty"`
	UtilityDir           string            `protobuf:"bytes,12,opt,name=utility_dir,json=utilityDir,proto3" json:"utility_dir,omitempty"`
	Location             string            `protobuf:"bytes,13,opt,name=location,proto3" json:"location,omitempty"`
	ContainerPlatform    string            `protobuf:"bytes,14,opt,name=container_platform,json=containerPlatform,proto3" json:"container_platform,omitempty"`
	Layout               string            `protobuf:"bytes,15,opt,name=layout,proto3" json:"layout,omitempty"`
	RealName             string            `protobuf:"bytes,16,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	DotALinkage          bool              `protobuf:"varint,17,opt,name=dot_a_linkage,json=dotALinkage,proto3" json:"dot_a_linkage,omitempty"`
	Precompiled          bool              `protobuf:"varint,18,opt,name=precompiled,proto3" json:"precompiled,omitempty"`
	LdFlags              string            `protobuf:"bytes,19,opt,name=ld_flags,json=ldFlags,proto3" json:"ld_flags,omitempty"`
	IsLegacy             bool              `protobuf:"varint,20,opt,name=is_legacy,json=isLegacy,proto3" json:"is_legacy,omitempty"`
	Version              string            `protobuf:"bytes,21,opt,name=version,proto3" json:"version,omitempty"`
	License              string            `protobuf:"bytes,22,opt,name=license,proto3" json:"license,omitempty"`
	Properties           map[string]string `protobuf:"bytes,23,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Library) Reset()         { *m = Library{} }
func (m *Library) String() string { return proto.CompactTextString(m) }
func (*Library) ProtoMessage()    {}
func (*Library) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{20}
}

func (m *Library) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Library.Unmarshal(m, b)
}
func (m *Library) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Library.Marshal(b, m, deterministic)
}
func (m *Library) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Library.Merge(m, src)
}
func (m *Library) XXX_Size() int {
	return xxx_messageInfo_Library.Size(m)
}
func (m *Library) XXX_DiscardUnknown() {
	xxx_messageInfo_Library.DiscardUnknown(m)
}

var xxx_messageInfo_Library proto.InternalMessageInfo

func (m *Library) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Library) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Library) GetMaintainer() string {
	if m != nil {
		return m.Maintainer
	}
	return ""
}

func (m *Library) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

func (m *Library) GetParagraph() string {
	if m != nil {
		return m.Paragraph
	}
	return ""
}

func (m *Library) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Library) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Library) GetArchitectures() []string {
	if m != nil {
		return m.Architectures
	}
	return nil
}

func (m *Library) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *Library) GetInstallDir() string {
	if m != nil {
		return m.InstallDir
	}
	return ""
}

func (m *Library) GetSourceDir() string {
	if m != nil {
		return m.SourceDir
	}
	return ""
}

func (m *Library) GetUtilityDir() string {
	if m != nil {
		return m.UtilityDir
	}
	return ""
}

func (m *Library) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Library) GetContainerPlatform() string {
	if m != nil {
		return m.ContainerPlatform
	}
	return ""
}

func (m *Library) GetLayout() string {
	if m != nil {
		return m.Layout
	}
	return ""
}

func (m *Library) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *Library) GetDotALinkage() bool {
	if m != nil {
		return m.DotALinkage
	}
	return false
}

func (m *Library) GetPrecompiled() bool {
	if m != nil {
		return m.Precompiled
	}
	return false
}

func (m *Library) GetLdFlags() string {
	if m != nil {
		return m.LdFlags
	}
	return ""
}

func (m *Library) GetIsLegacy() bool {
	if m != nil {
		return m.IsLegacy
	}
	return false
}

func (m *Library) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Library) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

func (m *Library) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func init() {
	proto.RegisterEnum("cc.arduino.cli.commands.LibraryLayout", LibraryLayout_name, LibraryLayout_value)
	proto.RegisterEnum("cc.arduino.cli.commands.LibraryLocation", LibraryLocation_name, LibraryLocation_value)
	proto.RegisterType((*LibraryDownloadReq)(nil), "cc.arduino.cli.commands.LibraryDownloadReq")
	proto.RegisterType((*LibraryDownloadResp)(nil), "cc.arduino.cli.commands.LibraryDownloadResp")
	proto.RegisterType((*LibraryInstallReq)(nil), "cc.arduino.cli.commands.LibraryInstallReq")
	proto.RegisterType((*LibraryInstallResp)(nil), "cc.arduino.cli.commands.LibraryInstallResp")
	proto.RegisterType((*LibraryUninstallReq)(nil), "cc.arduino.cli.commands.LibraryUninstallReq")
	proto.RegisterType((*LibraryUninstallResp)(nil), "cc.arduino.cli.commands.LibraryUninstallResp")
	proto.RegisterType((*LibraryUpgradeAllReq)(nil), "cc.arduino.cli.commands.LibraryUpgradeAllReq")
	proto.RegisterType((*LibraryUpgradeAllResp)(nil), "cc.arduino.cli.commands.LibraryUpgradeAllResp")
	proto.RegisterType((*LibraryResolveDependenciesReq)(nil), "cc.arduino.cli.commands.LibraryResolveDependenciesReq")
	proto.RegisterType((*LibraryResolveDependenciesResp)(nil), "cc.arduino.cli.commands.LibraryResolveDependenciesResp")
	proto.RegisterType((*LibraryDependencyStatus)(nil), "cc.arduino.cli.commands.LibraryDependencyStatus")
	proto.RegisterType((*LibrarySearchReq)(nil), "cc.arduino.cli.commands.LibrarySearchReq")
	proto.RegisterType((*LibrarySearchResp)(nil), "cc.arduino.cli.commands.LibrarySearchResp")
	proto.RegisterType((*SearchedLibrary)(nil), "cc.arduino.cli.commands.SearchedLibrary")
	proto.RegisterMapType((map[string]*LibraryRelease)(nil), "cc.arduino.cli.commands.SearchedLibrary.ReleasesEntry")
	proto.RegisterType((*LibraryRelease)(nil), "cc.arduino.cli.commands.LibraryRelease")
	proto.RegisterType((*LibraryDependency)(nil), "cc.arduino.cli.commands.LibraryDependency")
	proto.RegisterType((*DownloadResource)(nil), "cc.arduino.cli.commands.DownloadResource")
	proto.RegisterType((*LibraryListReq)(nil), "cc.arduino.cli.commands.LibraryListReq")
	proto.RegisterType((*LibraryListResp)(nil), "cc.arduino.cli.commands.LibraryListResp")
	proto.RegisterType((*InstalledLibrary)(nil), "cc.arduino.cli.commands.InstalledLibrary")
	proto.RegisterType((*Library)(nil), "cc.arduino.cli.commands.Library")
	proto.RegisterMapType((map[string]string)(nil), "cc.arduino.cli.commands.Library.PropertiesEntry")
}

func init() { proto.RegisterFile("commands/lib.proto", fileDescriptor_9feed0d29806df6c) }

var fileDescriptor_9feed0d29806df6c = []byte{
	// 1261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xdd, 0x6f, 0x1b, 0x45,
	0x10, 0xe7, 0xec, 0x36, 0xb1, 0xc7, 0x71, 0xed, 0x6c, 0xd3, 0xf6, 0x48, 0x69, 0x1b, 0x4e, 0x20,
	0xd2, 0x54, 0x75, 0x50, 0x91, 0x2a, 0x54, 0xa9, 0x42, 0x85, 0xb6, 0xa8, 0x28, 0xaa, 0xa2, 0xeb,
	0xc7, 0x03, 0x20, 0x9d, 0xd6, 0x77, 0x13, 0x7b, 0xe5, 0xf5, 0xed, 0x75, 0x77, 0xcf, 0x95, 0x79,
	0xe1, 0xeb, 0x95, 0x17, 0xde, 0x79, 0xe0, 0x05, 0x21, 0xf1, 0xc7, 0xf1, 0x37, 0xa0, 0xbd, 0xdd,
	0x3b, 0x7f, 0x24, 0x69, 0x03, 0x8a, 0x0a, 0xe2, 0x29, 0x37, 0x33, 0x3b, 0x33, 0xbf, 0x9d, 0x8f,
	0xdf, 0x3a, 0x40, 0x62, 0x31, 0x1e, 0xd3, 0x34, 0x51, 0xbb, 0x9c, 0xf5, 0x7b, 0x99, 0x14, 0x5a,
	0x90, 0x4b, 0x71, 0xdc, 0xa3, 0x32, 0xc9, 0x59, 0x2a, 0x7a, 0x31, 0x67, 0xbd, 0xf2, 0xc8, 0xe6,
	0x85, 0xea, 0xb0, 0xf9, 0x10, 0xa9, 0x3d, 0x1f, 0x7c, 0xef, 0x01, 0xd9, 0x63, 0x7d, 0x49, 0xe5,
	0xf4, 0xbe, 0x78, 0x99, 0x72, 0x41, 0x93, 0x10, 0x5f, 0x90, 0xbb, 0xd0, 0x60, 0xa9, 0xd2, 0x34,
	0x8d, 0xd1, 0xf7, 0xb6, 0xbc, 0xed, 0xd6, 0xad, 0x77, 0x7b, 0xc7, 0x44, 0xee, 0x3d, 0x72, 0x07,
	0xc3, 0xca, 0x85, 0x10, 0x38, 0x93, 0xd2, 0x31, 0xfa, 0xb5, 0x2d, 0x6f, 0xbb, 0x19, 0x16, 0xdf,
	0xc4, 0x87, 0xd5, 0x09, 0x4a, 0xc5, 0x44, 0xea, 0xd7, 0x0b, 0x75, 0x29, 0x06, 0x5f, 0xc3, 0xf9,
	0x43, 0x10, 0x54, 0x46, 0x1e, 0x40, 0x23, 0x93, 0x62, 0x20, 0x51, 0x29, 0x87, 0xe1, 0xfa, 0xb1,
	0x18, 0x4a, 0xc7, 0x7d, 0xe7, 0x10, 0x56, 0xae, 0xc1, 0x77, 0x1e, 0xac, 0xbb, 0xf0, 0x05, 0x52,
	0xce, 0xdf, 0xf8, 0x05, 0x7f, 0x9f, 0x15, 0xb9, 0x82, 0x70, 0x6a, 0x17, 0x24, 0x5f, 0x40, 0x5b,
	0x53, 0x35, 0x8a, 0xaa, 0x58, 0xb5, 0x22, 0xd6, 0xfb, 0xc7, 0xc6, 0x7a, 0x4a, 0xd5, 0xa8, 0x8a,
	0xb3, 0xa6, 0xe7, 0xa4, 0xe0, 0x07, 0xaf, 0xea, 0xc5, 0xb3, 0x94, 0xfd, 0x4b, 0xe5, 0xea, 0xc3,
	0xc6, 0x61, 0x0c, 0x2a, 0x3b, 0x7c, 0x51, 0xef, 0x9f, 0x5f, 0xf4, 0xd9, 0x2c, 0x47, 0x36, 0x90,
	0x34, 0xc1, 0x7b, 0xa7, 0x71, 0xd1, 0xe0, 0x0f, 0x0f, 0x2e, 0x1c, 0x11, 0xf7, 0xbf, 0xd9, 0xec,
	0x9f, 0x3c, 0xb8, 0xe2, 0xc0, 0x86, 0xa8, 0x04, 0x9f, 0xe0, 0x7d, 0xcc, 0x30, 0x4d, 0x30, 0x8d,
	0x19, 0xaa, 0x37, 0xde, 0xf6, 0x09, 0x5c, 0x7d, 0x15, 0x1a, 0x95, 0x91, 0xa7, 0xb0, 0x96, 0xcc,
	0xe9, 0x7c, 0x6f, 0xab, 0xbe, 0xdd, 0xba, 0xf5, 0xe1, 0xb1, 0x90, 0x4a, 0x56, 0x29, 0x7d, 0xa6,
	0x4f, 0x34, 0xd5, 0xb9, 0x0a, 0x17, 0xa2, 0x04, 0x3f, 0x7a, 0x70, 0xe9, 0x98, 0x93, 0xd5, 0x0d,
	0xbc, 0xb9, 0x1b, 0x6c, 0x43, 0xc7, 0x41, 0x0e, 0xf1, 0x45, 0xce, 0x24, 0x26, 0xee, 0x82, 0xcb,
	0x6a, 0xb2, 0x03, 0x5d, 0xa7, 0x72, 0x6b, 0x8f, 0x89, 0xbb, 0xf4, 0x21, 0x7d, 0x30, 0x80, 0xae,
	0x03, 0xf1, 0x04, 0xa9, 0x8c, 0x87, 0xa7, 0x50, 0xfe, 0x0d, 0x38, 0xfb, 0x22, 0x47, 0x39, 0x75,
	0xf0, 0xac, 0x10, 0x7c, 0x55, 0xd1, 0x61, 0x99, 0x48, 0x65, 0xe4, 0x21, 0x34, 0x79, 0xa1, 0x9c,
	0x95, 0x75, 0xfb, 0xd8, 0x54, 0xd6, 0x0f, 0x93, 0xb2, 0x5b, 0x33, 0xd7, 0xe0, 0xd7, 0x1a, 0x74,
	0x96, 0xcc, 0x47, 0xd6, 0x30, 0x84, 0x86, 0x44, 0x8e, 0x54, 0xa1, 0x99, 0x60, 0x93, 0xee, 0xf6,
	0x49, 0xd3, 0xf5, 0x42, 0xe7, 0xf8, 0x20, 0xd5, 0x72, 0x1a, 0x56, 0x71, 0xc8, 0x27, 0xb0, 0xc2,
	0xa9, 0x46, 0xa5, 0x8b, 0x1a, 0xb7, 0x6e, 0x7d, 0xf0, 0xba, 0xb9, 0x70, 0x81, 0x42, 0xe7, 0xb6,
	0x99, 0x40, 0x7b, 0x21, 0x36, 0xe9, 0x42, 0x7d, 0x84, 0x53, 0x07, 0xdc, 0x7c, 0x92, 0xbb, 0x70,
	0x76, 0x42, 0x79, 0x8e, 0x6e, 0xed, 0x4e, 0x9c, 0xc2, 0x7a, 0xdd, 0xa9, 0x7d, 0xec, 0x05, 0x7f,
	0xd6, 0xe1, 0xdc, 0xa2, 0x95, 0x5c, 0x84, 0x15, 0x9a, 0xeb, 0xa1, 0x90, 0x2e, 0x95, 0x93, 0xe6,
	0x77, 0xa5, 0xb6, 0xb0, 0x2b, 0xe4, 0x2a, 0xc0, 0x98, 0xb2, 0x54, 0x53, 0x96, 0xa2, 0x74, 0x33,
	0x35, 0xa7, 0x21, 0x9b, 0xd0, 0x50, 0x98, 0x6a, 0x34, 0x93, 0x73, 0xa6, 0xb0, 0x56, 0x32, 0x79,
	0x07, 0x9a, 0x19, 0x95, 0x74, 0x20, 0x69, 0x36, 0xf4, 0xcf, 0x16, 0xc6, 0x99, 0xc2, 0xe4, 0x7c,
	0x89, 0x7d, 0xc5, 0x34, 0xfa, 0x2b, 0x36, 0xa7, 0x13, 0x4d, 0xcc, 0x98, 0x6a, 0x1c, 0x08, 0x39,
	0xf5, 0x57, 0x6d, 0xcc, 0x52, 0x26, 0xef, 0x41, 0xdb, 0x34, 0x89, 0x69, 0x8c, 0x75, 0x2e, 0x51,
	0xf9, 0x8d, 0xad, 0xfa, 0x76, 0x33, 0x5c, 0x54, 0x9a, 0x81, 0xd4, 0xd3, 0x0c, 0x95, 0xdf, 0x2c,
	0xac, 0x56, 0x20, 0x9f, 0x43, 0x53, 0xa2, 0x12, 0xb9, 0x8c, 0x51, 0xf9, 0x70, 0x42, 0x6a, 0x0c,
	0x9d, 0x47, 0x38, 0xf3, 0x35, 0xd0, 0x39, 0x8b, 0x31, 0x55, 0xe8, 0xb7, 0x2c, 0x74, 0x27, 0x92,
	0x1b, 0xb0, 0x9e, 0x49, 0x31, 0x61, 0x09, 0xaa, 0x88, 0xa5, 0x31, 0xcf, 0x13, 0x54, 0xfe, 0x5a,
	0x01, 0xa2, 0x5b, 0x1a, 0x1e, 0x39, 0x3d, 0x79, 0xbc, 0xc4, 0x32, 0xed, 0x62, 0x3e, 0x77, 0x4e,
	0xce, 0x32, 0x4b, 0xfc, 0xf2, 0xbc, 0x5a, 0xb8, 0xd9, 0x91, 0x23, 0x97, 0xe2, 0x26, 0x10, 0xd7,
	0xdf, 0x28, 0x16, 0xa9, 0xd2, 0xd2, 0xf4, 0xd3, 0x75, 0x7e, 0xdd, 0x59, 0x3e, 0xab, 0x0c, 0xc1,
	0x2f, 0x1e, 0x74, 0x97, 0xcb, 0x61, 0x46, 0x36, 0x97, 0xbc, 0x1c, 0xd9, 0x5c, 0x72, 0x43, 0x57,
	0x45, 0x17, 0x26, 0x78, 0xc0, 0x38, 0xce, 0xf1, 0xf1, 0xb2, 0xba, 0x68, 0xf0, 0x10, 0xe3, 0x91,
	0xca, 0xc7, 0x6e, 0xa4, 0x2a, 0xd9, 0xe0, 0x55, 0xec, 0x1b, 0x3b, 0x4c, 0xf5, 0xb0, 0xf8, 0x36,
	0x83, 0x14, 0xd3, 0x78, 0x88, 0x19, 0xd5, 0xd5, 0x20, 0x55, 0x8a, 0xe0, 0xdb, 0x6a, 0xcc, 0xf7,
	0x98, 0xd2, 0xa7, 0x40, 0x67, 0x5d, 0xa8, 0x53, 0xce, 0x0b, 0xf0, 0x8d, 0xd0, 0x7c, 0x1a, 0x00,
	0x79, 0x96, 0x50, 0x4d, 0xfb, 0x1c, 0x0b, 0xc4, 0x8d, 0x70, 0xa6, 0x08, 0x18, 0x74, 0x16, 0x00,
	0xa8, 0x8c, 0x3c, 0x87, 0x75, 0x56, 0x32, 0x6e, 0x64, 0x59, 0x6b, 0xea, 0xe8, 0xee, 0xfa, 0xab,
	0xa1, 0x18, 0x8f, 0x72, 0x6b, 0xbb, 0x6c, 0x49, 0x13, 0xfc, 0xec, 0x41, 0x77, 0xf9, 0x18, 0xb9,
	0x63, 0xc6, 0xb1, 0x4c, 0x61, 0x6e, 0xbb, 0xf5, 0x5a, 0xb6, 0x28, 0x1d, 0xc8, 0x3d, 0x58, 0x75,
	0xbc, 0xf6, 0x77, 0x99, 0xa6, 0xf4, 0x0b, 0x7e, 0x5b, 0x81, 0xd5, 0x57, 0x51, 0xf0, 0x8c, 0x74,
	0x6a, 0x0b, 0xa4, 0xf3, 0x7f, 0xa2, 0x96, 0x6b, 0xd0, 0x72, 0xbd, 0x8a, 0x12, 0x26, 0x0b, 0x72,
	0x69, 0x86, 0xe0, 0x54, 0xf7, 0x99, 0x24, 0x57, 0x00, 0xec, 0xe2, 0x14, 0x76, 0xcb, 0x1a, 0x4d,
	0xab, 0x31, 0xe6, 0x6b, 0xd0, 0xca, 0x35, 0xe3, 0x4c, 0x4f, 0x0b, 0xfb, 0x9a, 0xf5, 0x77, 0x2a,
	0x73, 0x60, 0x13, 0x1a, 0x5c, 0xc4, 0x54, 0x1b, 0x8a, 0x6e, 0x5b, 0xe0, 0xa5, 0x6c, 0xd6, 0x39,
	0x16, 0xae, 0x6a, 0x51, 0xc6, 0xa9, 0x3e, 0x10, 0x72, 0xec, 0x9f, 0xb3, 0xeb, 0x5c, 0x59, 0xf6,
	0x9d, 0xc1, 0xf4, 0x83, 0xd3, 0xa9, 0xc8, 0xb5, 0xdf, 0xb1, 0xfd, 0xb0, 0x12, 0xb9, 0x6c, 0xe8,
	0x91, 0xf2, 0xa8, 0x68, 0x60, 0xd7, 0xe6, 0x30, 0x8a, 0xc7, 0xa6, 0x89, 0x01, 0xb4, 0x13, 0xa1,
	0x23, 0x1a, 0x71, 0x96, 0x8e, 0xe8, 0x00, 0xfd, 0xf5, 0x62, 0x0b, 0x5a, 0x89, 0xd0, 0xf7, 0xf6,
	0xac, 0x8a, 0x6c, 0x41, 0x2b, 0x93, 0x18, 0x8b, 0x71, 0xc6, 0xcc, 0x0f, 0x10, 0x62, 0x4f, 0xcc,
	0xa9, 0xc8, 0xdb, 0xd0, 0xe0, 0x49, 0x74, 0xc0, 0xe9, 0x40, 0xf9, 0xe7, 0x1d, 0x73, 0x26, 0x0f,
	0x8d, 0x68, 0xb2, 0x33, 0x15, 0x71, 0x1c, 0xd0, 0x78, 0xea, 0x6f, 0x14, 0xae, 0x0d, 0xa6, 0xf6,
	0x0a, 0x79, 0xfe, 0x7d, 0xba, 0xb0, 0xf8, 0x3e, 0xcd, 0x51, 0xf1, 0xc5, 0x45, 0x2a, 0xde, 0x07,
	0xc8, 0xa4, 0xc8, 0x50, 0x6a, 0xc3, 0xad, 0x97, 0x4e, 0xf6, 0x0b, 0xae, 0xb7, 0x5f, 0xb9, 0xd8,
	0x57, 0x7f, 0x2e, 0xc6, 0xe6, 0x5d, 0xe8, 0x2c, 0x99, 0x8f, 0x78, 0xb8, 0x37, 0xe6, 0x1f, 0xee,
	0xe6, 0xdc, 0x7b, 0xbc, 0x73, 0x1b, 0xda, 0x25, 0x4d, 0xd8, 0x82, 0x77, 0xa0, 0x75, 0xc0, 0xa9,
	0x8e, 0x6c, 0xfd, 0xbb, 0x6f, 0x91, 0x0d, 0xe8, 0x4a, 0x8c, 0x73, 0xa9, 0xd8, 0x04, 0x4b, 0xad,
	0xb7, 0x33, 0x47, 0x2f, 0x65, 0xc7, 0x3b, 0xd0, 0x62, 0x09, 0x46, 0xfd, 0x9c, 0x71, 0xcd, 0x52,
	0xeb, 0x59, 0x36, 0xbe, 0xd2, 0x7a, 0xe4, 0x1a, 0x5c, 0x96, 0x78, 0x80, 0xd2, 0xac, 0x4c, 0x12,
	0x1d, 0x3a, 0x50, 0x23, 0xe7, 0x00, 0xd4, 0x08, 0x75, 0x3c, 0xec, 0x0b, 0x31, 0xea, 0xd6, 0x3f,
	0xbd, 0xf9, 0xe5, 0x8d, 0x01, 0xd3, 0xc3, 0xbc, 0x6f, 0x0a, 0xb3, 0xeb, 0x0a, 0x55, 0xfe, 0xbd,
	0x19, 0x73, 0xb6, 0x2b, 0xb3, 0x78, 0xb7, 0x2c, 0x5a, 0x7f, 0xa5, 0xf8, 0xd7, 0xfe, 0xa3, 0xbf,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x02, 0x41, 0xe8, 0x67, 0x20, 0x10, 0x00, 0x00,
}
