# Source: https://github.com/arduino/tooling-project-assets/blob/main/issue-templates/forms/platform-dependent/feature-request.yml
# See: https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: Feature request
description: Suggest an enhancement to this project.
labels:
  - "type: enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Please see the [contributor guide](https://arduino.github.io/arduino-cli/dev/CONTRIBUTING/) for more information.
  - type: textarea
    id: description
    attributes:
      label: Describe the request
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Describe the current behavior
      description: |
        What is the current behavior of Arduino CLI in relation to your request?
        How can we reproduce that behavior?
    validations:
      required: true
  - type: input
    id: project-version
    attributes:
      label: Arduino CLI version
      description: |
        Which version of Arduino CLI are you using?
        (output of `arduino-cli version`)
        _This should be the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)._
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Which operating system(s) are you using on your computer?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - N/A
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating system version
      description: Which version of the operating system are you using on your computer?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any additional information here.
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Issue checklist
      description: Please double-check that you have done each of the following things before submitting the issue.
      options:
        - label: I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
          required: true
        - label: I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
          required: true
        - label: My request contains all necessary details
          required: true
