:source-highlighter: pygments
:pygments-style: manni

= Asciidoc in VS Code
Setup a fully working asciidoc environment in Visual Studio Code.
Alessandro Sanino <a.sanino@arduino.cc>

. Install Ascii Doctor (needs Python installed)
+
[source, bash]
----
$ gem install asciidoctor
----

. Install Extra Highlighters
+
[source, bash]
----
$ gem install pygments.rb #Pygments
$ gem install coderay     #Coderay
----

. Install the following plugins (Guide link:https://code.visualstudio.com/docs/editor/extension-gallery[Here])
.. `justusadam.language-asciidoc` : it has better highlighting of asciidoc documents

.. `joaompinto.asciidoctor-vscode` : enables previews

. Reload Visual Studio Code

=== Default Highlighters
`highlightjs` is an highlighter which is available without installation, but requires internet connection, since it is downloaded from a CDN.

=== Shortcuts

*CTRL+K R* (Press _CTRL+K first, then R key_) Enables the tab previews aside the current working document window.

*CTRL+SHIFT+R* Opens the preview over the current document window.